/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Proetale.WeilConjectures.ZetaFunction

/-!
# Convergence of the Euler product for arithmetic schemes

For a scheme `X` of finite type over `ℤ`, the Euler product defining the zeta function
of `X` converges on a right half-plane.

The proof is by counting: `X` is covered by finitely many affine charts `Spec A` with
`A` a finitely generated ring, and a finitely generated ring with `n` generators admits
at most `q ^ n` homomorphisms into a field with `q` elements, so `Spec A` has at most
`q ^ n` points of norm `q`. Hence `∑ N(x) ^ (-σ)` is dominated by a constant multiple of
`∑ q ^ (n - σ)`, which converges for `σ > n + 2`.

Serre's theorem 1 in [Serre, *Zeta and L functions*] gives the sharp abscissa
`σ > dim X`; we only prove the existence of a half-plane of convergence.

## Main statements

- `AlgebraicGeometry.Scheme.multipliable_eulerFactor_of_finiteType`
-/

universe u

open CategoryTheory

namespace AlgebraicGeometry.Scheme

variable (X : Scheme.{u})

/-- The range of any ring homomorphism out of a ring isomorphic to `ℤ` is contained in
every subring, since every subring contains all integer multiples of `1`. -/
private lemma range_subset_closure {R A : Type*} [CommRing R] [CommRing A]
    (e : ℤ ≃+* R) (φ : R →+* A) (u : Set A) :
    Set.range ⇑φ ⊆ ↑(Subring.closure u) := by
  rintro - ⟨x, rfl⟩
  obtain ⟨n, rfl⟩ := e.surjective x
  have h : φ (e n) = (n : A) := by simp
  rw [h]
  exact intCast_mem _ n

/-- The ring of global sections of an affine scheme of finite type over `ℤ` is finitely
generated as a ring. -/
private lemma exists_finset_closure_eq_top {U : Scheme.{u}} [IsAffine U]
    (g : U ⟶ Spec (.of (ULift.{u} ℤ))) [LocallyOfFiniteType g] :
    ∃ t : Finset Γ(U, ⊤), Subring.closure (↑t : Set Γ(U, ⊤)) = ⊤ := by
  have hft : RingHom.FiniteType (g.appTop).hom :=
    (HasRingHomProperty.iff_of_isAffine (P := @LocallyOfFiniteType)).mp ‹LocallyOfFiniteType g›
  letI : Algebra Γ(Spec (.of (ULift.{u} ℤ)), ⊤) Γ(U, ⊤) := (g.appTop).hom.toAlgebra
  have halg : Algebra.FiniteType Γ(Spec (.of (ULift.{u} ℤ)), ⊤) Γ(U, ⊤) := hft
  obtain ⟨t, ht⟩ := halg.out
  refine ⟨t, ?_⟩
  have hcl : Subring.closure
      (Set.range (algebraMap Γ(Spec (.of (ULift.{u} ℤ)), ⊤) Γ(U, ⊤)) ∪ ↑t) = ⊤ := by
    have h := Algebra.adjoin_eq_ring_closure (R := Γ(Spec (.of (ULift.{u} ℤ)), ⊤))
      (↑t : Set Γ(U, ⊤))
    rw [ht] at h
    rw [← h]
    exact Algebra.top_toSubring
  have hrange : Set.range (algebraMap Γ(Spec (.of (ULift.{u} ℤ)), ⊤) Γ(U, ⊤)) ⊆
      ↑(Subring.closure (↑t : Set Γ(U, ⊤))) :=
    range_subset_closure
      (((ULift.ringEquiv : ULift.{u} ℤ ≃+* ℤ)).symm.trans
        (Scheme.ΓSpecIso (.of (ULift.{u} ℤ))).commRingCatIsoToRingEquiv.symm) _ _
  refine le_antisymm le_top ?_
  rw [← hcl]
  exact Subring.closure_le.mpr (Set.union_subset hrange Subring.subset_closure)

/-- A ring generated by a finite set `s` admits at most `#F ^ #s` homomorphisms into a
finite ring `F`, and only finitely many. -/
private lemma finite_and_card_ringHom_le {A F : Type*} [CommRing A] [CommRing F] [Finite F]
    (s : Finset A) (hcl : Subring.closure (↑s : Set A) = ⊤) :
    Finite (A →+* F) ∧ Nat.card (A →+* F) ≤ Nat.card F ^ s.card := by
  have hinj : Function.Injective fun (φ : A →+* F) (x : ↑s) ↦ φ x.1 := by
    intro φ ψ h
    have hle : Subring.closure (↑s : Set A) ≤ φ.eqLocus ψ :=
      Subring.closure_le.mpr fun x hx ↦ congrFun h ⟨x, hx⟩
    ext a
    exact hle (by rw [hcl]; exact Subring.mem_top a)
  refine ⟨Finite.of_injective _ hinj, ?_⟩
  calc Nat.card (A →+* F) ≤ Nat.card (↑s → F) := Nat.card_le_card_of_injective _ hinj
    _ = Nat.card F ^ s.card := by rw [Nat.card_fun, Nat.card_eq_finsetCard]

/-- If `A` is generated as a ring by `n` elements, the spectrum of `A` has at most
`q ^ n` points whose residue field has exactly `q` elements. -/
private lemma finite_and_card_fiber_le {A : Type*} [CommRing A] (s : Finset A)
    (hcl : Subring.closure (↑s : Set A) = ⊤) {q : ℕ} (hq : 2 ≤ q) :
    Finite {y : PrimeSpectrum A // Nat.card y.asIdeal.ResidueField = q} ∧
      Nat.card {y : PrimeSpectrum A // Nat.card y.asIdeal.ResidueField = q} ≤ q ^ s.card := by
  rcases isEmpty_or_nonempty {y : PrimeSpectrum A // Nat.card y.asIdeal.ResidueField = q} with
    he | hne
  · haveI := he
    exact ⟨Finite.of_fintype _, by rw [Nat.card_of_isEmpty]; exact Nat.zero_le _⟩
  obtain ⟨⟨y₀, hy₀⟩⟩ := hne
  haveI : Finite y₀.asIdeal.ResidueField :=
    Nat.finite_of_card_ne_zero (by rw [hy₀]; omega)
  have hequiv : ∀ y : {y : PrimeSpectrum A // Nat.card y.asIdeal.ResidueField = q},
      Nonempty (y.1.asIdeal.ResidueField ≃+* y₀.asIdeal.ResidueField) := by
    intro y
    haveI : Finite y.1.asIdeal.ResidueField :=
      Nat.finite_of_card_ne_zero (by rw [y.2]; omega)
    haveI := Fintype.ofFinite y.1.asIdeal.ResidueField
    haveI := Fintype.ofFinite y₀.asIdeal.ResidueField
    exact ⟨FiniteField.ringEquivOfCardEq (by
      rw [← Nat.card_eq_fintype_card, ← Nat.card_eq_fintype_card, y.2, hy₀])⟩
  have e := fun y ↦ (hequiv y).some
  have hker : ∀ y : {y : PrimeSpectrum A // Nat.card y.asIdeal.ResidueField = q},
      RingHom.ker ((e y).toRingHom.comp (algebraMap A y.1.asIdeal.ResidueField)) =
        y.1.asIdeal := by
    intro y
    ext a
    rw [RingHom.mem_ker, RingHom.comp_apply,
      ← Ideal.algebraMap_residueField_eq_zero (I := y.1.asIdeal) (x := a)]
    exact ⟨fun h0 ↦ (e y).injective (by rw [map_zero]; exact h0),
      fun h0 ↦ by rw [h0, map_zero]⟩
  have hinj : Function.Injective
      fun y : {y : PrimeSpectrum A // Nat.card y.asIdeal.ResidueField = q} ↦
        (e y).toRingHom.comp (algebraMap A y.1.asIdeal.ResidueField) := by
    intro y₁ y₂ h
    apply Subtype.ext
    apply PrimeSpectrum.ext
    rw [← hker y₁, ← hker y₂]
    exact congrArg RingHom.ker h
  obtain ⟨hfin, hcard⟩ := finite_and_card_ringHom_le (F := y₀.asIdeal.ResidueField) s hcl
  haveI := hfin
  refine ⟨Finite.of_injective _ hinj, ?_⟩
  calc Nat.card {y : PrimeSpectrum A // Nat.card y.asIdeal.ResidueField = q}
      ≤ Nat.card (A →+* y₀.asIdeal.ResidueField) := Nat.card_le_card_of_injective _ hinj
    _ ≤ Nat.card y₀.asIdeal.ResidueField ^ s.card := hcard
    _ = q ^ s.card := by rw [hy₀]

/-- Summability of `∑ N(y) ^ (-σ)` over the spectrum of a finitely generated ring, for
`σ` larger than the number of generators plus two. Points with infinite residue field
contribute `0` by the junk value convention of `Nat.card`. -/
private lemma summable_primeSpectrum {A : Type*} [CommRing A] (s : Finset A)
    (hcl : Subring.closure (↑s : Set A) = ⊤) {σ : ℝ} (hσ : (s.card : ℝ) + 2 ≤ σ) :
    Summable fun y : PrimeSpectrum A ↦ (Nat.card y.asIdeal.ResidueField : ℝ) ^ (-σ) := by
  have hs0 : (0 : ℝ) ≤ (s.card : ℝ) := Nat.cast_nonneg _
  have hσpos : 0 < σ := by linarith
  set c : PrimeSpectrum A → ℕ := fun y ↦ Nat.card y.asIdeal.ResidueField with hc
  have hone : ∀ y : PrimeSpectrum A, c y ≠ 1 := by
    intro y hy
    obtain ⟨hsub, -⟩ := Nat.card_eq_one_iff_unique.mp hy
    exact one_ne_zero (Subsingleton.elim (1 : y.asIdeal.ResidueField) 0)
  have hfiber : ∀ q : ℕ, Summable fun _y : {y : PrimeSpectrum A // c y = q} ↦ (q : ℝ) ^ (-σ) := by
    intro q
    rcases eq_or_ne q 0 with rfl | hq0
    · refine summable_zero.congr fun y ↦ ?_
      rw [Nat.cast_zero, Real.zero_rpow (neg_ne_zero.mpr hσpos.ne')]
    rcases eq_or_ne q 1 with rfl | hq1
    · haveI : IsEmpty {y : PrimeSpectrum A // c y = 1} := ⟨fun y ↦ hone y.1 y.2⟩
      exact summable_empty
    haveI : Finite {y : PrimeSpectrum A // c y = q} :=
      (finite_and_card_fiber_le s hcl (by omega)).1
    exact .of_finite
  have htsum : ∀ q : ℕ,
      ∑' _y : {y : PrimeSpectrum A // c y = q}, (q : ℝ) ^ (-σ) ≤
        (q : ℝ) ^ ((s.card : ℝ) - σ) := by
    intro q
    rcases eq_or_ne q 0 with rfl | hq0
    · have hL : ∑' _y : {y : PrimeSpectrum A // c y = 0}, ((0 : ℕ) : ℝ) ^ (-σ) = 0 := by
        simp [Real.zero_rpow (neg_ne_zero.mpr hσpos.ne')]
      rw [hL]
      exact Real.rpow_nonneg (Nat.cast_nonneg _) _
    rcases eq_or_ne q 1 with rfl | hq1
    · haveI : IsEmpty {y : PrimeSpectrum A // c y = 1} := ⟨fun y ↦ hone y.1 y.2⟩
      rw [tsum_empty]
      exact Real.rpow_nonneg (Nat.cast_nonneg _) _
    obtain ⟨hfin, hcard⟩ := finite_and_card_fiber_le s hcl (q := q) (by omega)
    haveI := hfin
    have hqpos : (0 : ℝ) < (q : ℝ) := by
      exact_mod_cast Nat.pos_of_ne_zero hq0
    rw [tsum_const, nsmul_eq_mul]
    calc (Nat.card {y : PrimeSpectrum A // c y = q} : ℝ) * (q : ℝ) ^ (-σ)
        ≤ ((q ^ s.card : ℕ) : ℝ) * (q : ℝ) ^ (-σ) :=
          mul_le_mul_of_nonneg_right (Nat.cast_le.mpr hcard)
            (Real.rpow_nonneg (Nat.cast_nonneg _) _)
      _ = (q : ℝ) ^ (s.card : ℝ) * (q : ℝ) ^ (-σ) := by
          rw [Nat.cast_pow, ← Real.rpow_natCast]
      _ = (q : ℝ) ^ ((s.card : ℝ) - σ) := by
          rw [← Real.rpow_add hqpos, ← sub_eq_add_neg]
  have hsum2 : Summable fun q : ℕ ↦
      ∑' _y : {y : PrimeSpectrum A // c y = q}, (q : ℝ) ^ (-σ) := by
    refine Summable.of_nonneg_of_le
      (fun q ↦ tsum_nonneg fun y ↦ Real.rpow_nonneg (Nat.cast_nonneg _) _) htsum ?_
    exact Real.summable_nat_rpow.mpr (by linarith)
  have hsigma : Summable fun p : Σ q : ℕ, {y : PrimeSpectrum A // c y = q} ↦
      (p.1 : ℝ) ^ (-σ) :=
    (summable_sigma_of_nonneg fun p ↦ Real.rpow_nonneg (Nat.cast_nonneg _) _).mpr
      ⟨hfiber, hsum2⟩
  refine (Equiv.summable_iff (Equiv.sigmaFiberEquiv c)).mp ?_
  refine hsigma.congr fun p ↦ ?_
  obtain ⟨q, y, hy⟩ := p
  exact congrArg (fun n : ℕ ↦ (n : ℝ) ^ (-σ)) hy.symm

/-- The norm of a point in the image of an open immersion from an affine scheme is
computed by the residue field of the corresponding prime ideal of the coordinate ring. -/
private lemma pointNorm_eq_chart {U : Scheme.{u}} [IsAffine U] (g : U ⟶ X)
    [IsOpenImmersion g] (y : U) :
    X.pointNorm (g y) = Nat.card (U.isoSpec.hom y).asIdeal.ResidueField :=
  Nat.card_congr <|
    ((asIso (g.residueFieldMap y)).commRingCatIsoToRingEquiv.toEquiv.trans
      (asIso (U.isoSpec.hom.residueFieldMap y)).commRingCatIsoToRingEquiv.toEquiv.symm).trans
      (Spec.residueFieldIso Γ(U, ⊤) (U.isoSpec.hom y)).commRingCatIsoToRingEquiv.toEquiv

/-- The analytic half of the convergence theorem: if the series `∑ N(x) ^ (-s)` converges
absolutely for some `s` with `1 ≤ re s`, then the Euler product converges at `s`. -/
private lemma multipliable_of_summable_norm {z : ℂ} (hz : 1 ≤ z.re)
    (h : Summable fun x : X.finitePoints ↦ ‖(X.pointNorm x.1 : ℂ) ^ (-z)‖) :
    Multipliable fun x : X.finitePoints ↦ X.eulerFactor x.1 z := by
  have hnorm : ∀ x : X.finitePoints, ‖(X.pointNorm x.1 : ℂ) ^ (-z)‖ ≤ 2⁻¹ := by
    intro x
    rw [Complex.norm_natCast_cpow_of_pos (X.pointNorm_pos x.2)]
    have h2 : (2 : ℝ) ≤ (X.pointNorm x.1 : ℝ) := by exact_mod_cast X.one_lt_pointNorm x.2
    have hle : (-z).re ≤ -1 := by rw [Complex.neg_re]; linarith
    calc (X.pointNorm x.1 : ℝ) ^ (-z).re
        ≤ (2 : ℝ) ^ (-z).re := Real.rpow_le_rpow_of_nonpos (by norm_num) h2 (by linarith)
      _ ≤ (2 : ℝ) ^ (-1 : ℝ) := Real.rpow_le_rpow_of_exponent_le one_le_two hle
      _ = 2⁻¹ := Real.rpow_neg_one 2
  have hne0 : ∀ x : X.finitePoints, (1 : ℂ) - (X.pointNorm x.1 : ℂ) ^ (-z) ≠ 0 := by
    intro x h0
    have h1 := norm_sub_norm_le (1 : ℂ) ((X.pointNorm x.1 : ℂ) ^ (-z))
    rw [h0, norm_zero, norm_one] at h1
    linarith [hnorm x]
  have hinv : ∀ x : X.finitePoints, ‖(1 - (X.pointNorm x.1 : ℂ) ^ (-z))⁻¹‖ ≤ 2 := by
    intro x
    have h1 := norm_sub_norm_le (1 : ℂ) ((X.pointNorm x.1 : ℂ) ^ (-z))
    rw [norm_one] at h1
    rw [norm_inv]
    calc ‖1 - (X.pointNorm x.1 : ℂ) ^ (-z)‖⁻¹
        ≤ ((2 : ℝ)⁻¹)⁻¹ := inv_anti₀ (by norm_num) (by linarith [hnorm x])
      _ = 2 := inv_inv 2
  have hw : Summable fun x : X.finitePoints ↦
      (X.pointNorm x.1 : ℂ) ^ (-z) * (1 - (X.pointNorm x.1 : ℂ) ^ (-z))⁻¹ := by
    refine Summable.of_norm_bounded (h.mul_right 2) fun x ↦ ?_
    rw [norm_mul]
    exact mul_le_mul_of_nonneg_left (hinv x) (norm_nonneg _)
  refine (Complex.multipliable_one_add_of_summable hw).congr fun x ↦ ?_
  have h1 : ((1 : ℂ) - (X.pointNorm x.1 : ℂ) ^ (-z)) *
      (1 - (X.pointNorm x.1 : ℂ) ^ (-z))⁻¹ = 1 := mul_inv_cancel₀ (hne0 x)
  calc 1 + (X.pointNorm x.1 : ℂ) ^ (-z) * (1 - (X.pointNorm x.1 : ℂ) ^ (-z))⁻¹
      = ((1 - (X.pointNorm x.1 : ℂ) ^ (-z)) + (X.pointNorm x.1 : ℂ) ^ (-z)) *
          (1 - (X.pointNorm x.1 : ℂ) ^ (-z))⁻¹ := by rw [add_mul, h1]
    _ = (1 - (X.pointNorm x.1 : ℂ) ^ (-z))⁻¹ := by ring
    _ = X.eulerFactor x.1 z := rfl

/-- For a scheme of finite type over `ℤ`, the Euler product defining the zeta function
converges on a right half-plane. (For `X` of dimension `d` one can take `a = d`, but we
do not state this.) -/
theorem multipliable_eulerFactor_of_finiteType (f : X ⟶ Spec (.of (ULift.{u} ℤ)))
    [LocallyOfFiniteType f] [QuasiCompact f] :
    ∃ a : ℝ, ∀ s : ℂ, a < s.re →
      Multipliable fun x : X.finitePoints ↦ X.eulerFactor x.1 s := by
  haveI : CompactSpace X := QuasiCompact.compactSpace_of_compactSpace f
  let 𝒰 : X.OpenCover := X.affineCover.finiteSubcover
  haveI : Fintype 𝒰.I₀ := inferInstanceAs (Fintype X.affineCover.finiteSubcover.I₀)
  haveI : ∀ i, IsAffine (𝒰.X i) := fun i ↦ inferInstanceAs (IsAffine (X.affineCover.X _))
  have hgen : ∀ i, ∃ t : Finset Γ(𝒰.X i, ⊤),
      Subring.closure (↑t : Set Γ(𝒰.X i, ⊤)) = ⊤ := fun i ↦
    exists_finset_closure_eq_top (𝒰.f i ≫ f)
  choose t ht using hgen
  refine ⟨(∑ i, ((t i).card : ℝ)) + 2, fun z hz ↦ ?_⟩
  have hsum0 : (0 : ℝ) ≤ ∑ i, ((t i).card : ℝ) :=
    Finset.sum_nonneg fun i _ ↦ Nat.cast_nonneg _
  refine multipliable_of_summable_norm X (by linarith) ?_
  have key : Summable fun x : X.finitePoints ↦ (X.pointNorm x.1 : ℝ) ^ (-z.re) := by
    refine (summable_partition (fun x ↦ Real.rpow_nonneg (Nat.cast_nonneg _) _)
      (s := fun i ↦ {x : X.finitePoints | 𝒰.idx x.1 = i})
      (fun x ↦ ⟨𝒰.idx x.1, rfl, fun j hj ↦ hj.symm⟩)).mpr
      ⟨fun i ↦ ?_, Summable.of_finite⟩
    have hle : ((t i).card : ℝ) ≤ ∑ j, ((t j).card : ℝ) :=
      Finset.single_le_sum (f := fun j ↦ ((t j).card : ℝ))
        (fun j _ ↦ Nat.cast_nonneg _) (Finset.mem_univ i)
    have hchart := summable_primeSpectrum (t i) (ht i) (σ := z.re) (by linarith)
    have hmem : ∀ x : {x : X.finitePoints | 𝒰.idx x.1 = i}, x.1.1 ∈ Set.range ⇑(𝒰.f i) := by
      intro x
      have hidx : 𝒰.idx x.1.1 = i := x.2
      have hx := 𝒰.covers x.1.1
      rw [hidx] at hx
      exact hx
    choose y hy using hmem
    have hinj : Function.Injective fun x : {x : X.finitePoints | 𝒰.idx x.1 = i} ↦
        (𝒰.X i).isoSpec.hom (y x) := by
      intro x₁ x₂ hx
      have h' : y x₁ = y x₂ := (𝒰.X i).isoSpec.hom.isOpenEmbedding.injective hx
      apply Subtype.ext
      apply Subtype.ext
      rw [← hy x₁, ← hy x₂, h']
    refine (hchart.comp_injective hinj).congr fun x ↦ ?_
    have hpn := pointNorm_eq_chart X (𝒰.f i) (y x)
    rw [hy x] at hpn
    simp only [Function.comp_apply]
    rw [← hpn]
  exact key.congr fun x ↦ by
    rw [Complex.norm_natCast_cpow_of_pos (X.pointNorm_pos x.2), Complex.neg_re]

end AlgebraicGeometry.Scheme
