/-
Copyright (c) 2025 Jiedong Jiang, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiedong Jiang, Christian Merten
-/
import Proetale.Mathlib.Topology.Inseparable
import Mathlib.Topology.Spectral.Basic
import Mathlib.Topology.JacobsonSpace
import Mathlib.Data.Set.Card
import Mathlib.Topology.Connected.Separation

/-!
# Constructible topology

In this file we define the constructible topology on a topological space. This is the topology
generated by compact open subsets and their complements.
-/

variable {X : Type*} [TopologicalSpace X]

/-- The constructible topology on a topological space `X` has as a subbasis
the open and compact sets of `X` and their complements. -/
def constructibleTopology (X : Type*) [TopologicalSpace X] : TopologicalSpace X :=
  .generateFrom ({ s | IsOpen s ∧ IsCompact s } ∪ { s | IsClosed s ∧ IsCompact sᶜ })

/-- A type synonym for `X` that is equipped with the constructible topology of `X`. -/
def WithConstructibleTopology (X : Type*) [TopologicalSpace X] : Type _ :=
  X

instance : TopologicalSpace (WithConstructibleTopology X) :=
  constructibleTopology X

open Topology

lemma IsCompact.isOpen_constructibleTopology_of_isOpen {s : Set X}
    (hs : IsCompact s) (ho : IsOpen s) : IsOpen[constructibleTopology X] s := by
  apply TopologicalSpace.isOpen_generateFrom_of_mem
  simp [ho, hs]

lemma IsCompact.isOpen_constructibleTopology_of_isClosed {s : Set X}
    (hs : IsCompact sᶜ) (ho : IsClosed s) : IsOpen[constructibleTopology X] s := by
  apply TopologicalSpace.isOpen_generateFrom_of_mem
  simp [ho, hs]

lemma compactSpace_generateFrom_of_compl_mem {X : Type*} [T : TopologicalSpace X]
    (𝔅 : Set (Set X)) (hT : T = TopologicalSpace.generateFrom 𝔅)
    (h𝔅 : ∀ s ∈ 𝔅, sᶜ ∈ 𝔅)
    (h : ∀ P ⊆ 𝔅, (∀ Q ⊆ P, Q.Finite → (⋂₀ Q).Nonempty) → (⋂₀ P).Nonempty) :
    CompactSpace X := by
  apply compactSpace_generateFrom hT
  intro P hP𝔅 hP
  contrapose! hP
  simp_rw [← Set.nonempty_compl, Set.compl_sUnion] at hP ⊢
  apply h
  · rintro _ ⟨S, hS, rfl⟩
    exact h𝔅 _ (hP𝔅 hS)
  · intro Q hQP hQ
    specialize @hP (compl '' Q)
    replace hP : Q ⊆ compl '' P → (compl '' Q).Finite → (⋂₀ Q).Nonempty := by
      simpa only [Set.image_subset_iff, Set.sInter_image, Set.mem_image, Set.iInter_exists,
        Set.biInter_and', Set.iInter_iInter_eq_right, compl_compl, Set.nonempty_iInter,
        Set.mem_iInter, ← compl_involutive.image_eq_preimage_symm] using hP
    exact hP hQP (hQ.image _)

/-- A spectral space is compact in the constructible topology. -/
@[stacks 0901]
instance compactSpace_withConstructibleTopology [SpectralSpace X] :
    CompactSpace (WithConstructibleTopology X) := by
  let 𝔅 := { s : Set X | IsOpen s ∧ IsCompact s } ∪ { s | IsClosed s ∧ IsCompact sᶜ }
  apply compactSpace_generateFrom_of_compl_mem (T := constructibleTopology X) 𝔅 rfl
  · intro s hs
    refine (Or.symm hs).imp ?_ (by simp)
    simp_all only [Set.mem_union, Set.mem_setOf_eq, isOpen_compl_iff, and_self, implies_true, 𝔅]
  let 𝒮 := {P : Set (Set X) | P ⊆ 𝔅 ∧ (∀ Q ⊆ P, Q.Finite → (⋂₀ Q).Nonempty) ∧ (⋂₀ P) = ∅}
  suffices 𝒮 = ∅ by
    contrapose! this
    rcases this with ⟨P, hP⟩
    refine ⟨P, hP⟩
  by_contra! h𝒮
  obtain ⟨s, hs⟩ := h𝒮
  have := (zorn_subset_nonempty 𝒮 ?zorn_condition s hs)
  case zorn_condition =>
    rintro c hc𝒮 hc ⟨x, hxc⟩
    have foo : ∀ s ∈ c, s ⊆ ⋃₀ c := by
      intro S hSc
      exact Set.subset_sUnion_of_subset c S (fun ⦃a⦄ a ↦ a) hSc
    refine ⟨⋃₀ c, ?_, foo⟩
    simp only [Set.mem_setOf_eq, Set.sUnion_subset_iff, 𝒮]
    refine ⟨?_, ?_, ?_⟩
    · grind
    · intro a hac ha
      suffices ∃ i ∈ c, a ⊆ i by
        obtain ⟨i, hic, hai⟩ := this
        exact (hc𝒮 hic).2.1 a hai ha
      induction h_card : a.ncard generalizing a with
      | zero =>
        simp_all only [Set.ncard_eq_zero, Set.empty_subset, and_true, Set.finite_empty]
        refine ⟨_, hxc⟩
      | succ n ih =>
        have : Finite a := ha
        rw [Set.ncard_eq_succ] at h_card
        rcases h_card with ⟨z, a, hza, rfl, h_card⟩
        obtain ⟨i, hic, hai⟩ := ih a (by grind) (by exact Set.finite_insert.mp ha) h_card
        have hz : z ∈ ⋃₀ c := by grind
        simp only [Set.mem_sUnion] at hz
        obtain ⟨t, htc, hzt⟩ := hz
        obtain rfl | hit := eq_or_ne i t
        · grind
        · specialize hc hic htc hit
          grind
    · grind
  obtain ⟨B, hsB, hB⟩ := this
  have hB𝒮 : B ∈ 𝒮 := hB.prop
  let B' := {s | s ∈ B ∧ IsClosed s}
  let Z := ⋂₀ B'
  have hZ_closed : IsClosed Z := isClosed_sInter fun b hb ↦ hb.2
  have hZ_nonempty : Z.Nonempty := by
    dsimp [Z]
    rw [Set.sInter_eq_iInter]
    apply CompactSpace.iInter_nonempty (fun b ↦ b.2.2)
    intro s
    dsimp [𝒮] at hB𝒮
    let s' : Set (Set X) := by classical exact (s.image Subtype.val : Set (Set X))
    have hsB : s' ⊆ B := by
      intro x
      simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe, Subtype.exists,
        exists_and_right, exists_eq_right, forall_exists_index, s']
      grind
    have := hB𝒮.2.1 s' hsB (Finset.finite_toSet _)
    simpa [s'] using this
  by_cases hZ_irred : IsIrreducible Z
  · suffices (⋂₀ B).Nonempty by
      have := hB𝒮.2.2
      simp_all
    have hη := hZ_irred.isGenericPoint_genericPoint hZ_closed
    set η := hZ_irred.genericPoint
    refine ⟨η, ?_⟩
    rw [Set.mem_sInter]
    intro i hi
    by_cases hiB' : i ∈ B'
    · suffices Z ⊆ i from this hη.mem
      apply Set.sInter_subset_of_mem hiB'
    · have hi_open : IsOpen i := by grind
      have hi_cmpt : IsCompact i := by grind
      rw [hη.mem_open_set_iff hi_open, Set.inter_comm]
      dsimp [Z]
      rw [Set.sInter_eq_iInter]
      apply hi_cmpt.inter_iInter_nonempty
      · exact fun b ↦ b.2.2
      · intro A
        have := hB𝒮.2.1 (insert i (by classical exact (A.image Subtype.val : Set (Set X)))) ?sg1 ?sg2
        case sg1 =>
          intro x
          simp only [Finset.coe_image, Set.mem_insert_iff, Set.mem_image, Finset.mem_coe,
            Subtype.exists, exists_and_right, exists_eq_right]
          grind
        case sg2 =>
          classical
          exact Set.toFinite (insert i (Finset.image Subtype.val A))
        classical
        apply this.mono
        rw [Set.sInter_insert]
        intro z ⟨hzi, hzA⟩
        refine Set.mem_inter hzi ?_
        rw [Set.mem_iInter]
        intro ⟨j, hjB'⟩
        rw [Set.mem_iInter]
        intro hjA
        apply hzA
        simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe, Subtype.exists,
          exists_and_right, exists_eq_right]
        exact ⟨hjB', hjA⟩
  · unfold IsIrreducible IsPreirreducible  at hZ_irred
    simp only [hZ_nonempty, true_and, not_forall] at hZ_irred
    rcases hZ_irred with ⟨U₁, U₂, hU₁, hU₂, hU₁Z, hU₂Z, hU₁₂⟩
    rw [Set.not_nonempty_iff_eq_empty, ← Set.subset_empty_iff] at hU₁₂
    obtain ⟨x₁, hx₁⟩ : ∃ x₁ ∈ U₁, x₁ ∈ Z ∧ x₁ ∉ U₂ := by
      obtain ⟨x, hx⟩ := hU₁Z
      -- on `4.24.0-rc1` this was `grind`
      use x, hx.2, hx.1
      intro h₂
      exact hU₁₂ ⟨hx.1, hx.2, h₂⟩
    obtain ⟨x₂, hx₂⟩ : ∃ x₂ ∈ U₂, x₂ ∈ Z ∧ x₂ ∉ U₁ := by
      obtain ⟨x, hx⟩ := hU₂Z
      -- on `4.24.0-rc1` this was `grind`
      use x, hx.2, hx.1
      intro h₁
      exact hU₁₂ ⟨hx.1, h₁, hx.2⟩
    have psp_X : PrespectralSpace X := inferInstance
    rw [prespectralSpace_iff] at psp_X
    rw [psp_X.isOpen_iff] at hU₁ hU₂
    obtain ⟨W₁, hW₁⟩ := hU₁ x₁ hx₁.1
    obtain ⟨W₂, hW₂⟩ := hU₂ x₂ hx₂.1
    have hW₁' : W₁ ∩ (Z \ U₁) ⊆ ∅ := by grind
    have hW₂' : W₂ ∩ (Z \ U₂) ⊆ ∅ := by grind
    let Y₁ := W₁ᶜ
    let Y₂ := W₂ᶜ
    have hY₁_cl : IsClosed Y₁ := by dsimp [Y₁]; simpa using hW₁.1.1
    have hY₂_cl : IsClosed Y₂ := by dsimp [Y₂]; simpa using hW₂.1.1
    have hY₁ : Y₁ ∈ 𝔅 := by
      right
      dsimp [Y₁]
      simp only [isClosed_compl_iff, compl_compl, hW₁.1.1, hW₁.1.2, true_and]
    have hY₂ : Y₂ ∈ 𝔅 := by
      right
      dsimp [Y₂]
      simp only [isClosed_compl_iff, compl_compl, hW₂.1.1, hW₂.1.2, true_and]
    have hY₁B : insert Y₁ B ∉ 𝒮 := by
      intro hY₁B
      have : insert Y₁ B ⊆ B := hB.le_of_ge hY₁B (Set.subset_insert Y₁ B)
      rw [Set.insert_subset_iff] at this
      grind
    have hY₂B : insert Y₂ B ∉ 𝒮 := by
      intro hY₂B
      have : insert Y₂ B ⊆ B := hB.le_of_ge hY₂B (Set.subset_insert Y₂ B)
      rw [Set.insert_subset_iff] at this
      grind
    have hY₁_inter_B : Y₁ ∩ ⋂₀ B = ∅ := by grind
    have hY₂_inter_B : Y₂ ∩ ⋂₀ B = ∅ := by grind
    dsimp [𝒮] at hY₁B hY₂B
    simp only [Set.insert_subset_iff, hY₁, hB𝒮.1, and_self, Set.sInter_insert, hY₁_inter_B,
      and_true, true_and, not_forall, Set.not_nonempty_iff_eq_empty, hY₂, hY₂_inter_B] at hY₁B hY₂B
    rcases hY₁B with ⟨A₁, hA₁, hA₁', hA₁''⟩
    rcases hY₂B with ⟨A₂, hA₂, hA₂', hA₂''⟩
    have : Z ⊆ Y₁ ∪ Y₂ := by
      -- on `4.24.0-rc1` this was `grind`
      intro z hz
      by_contra! hc
      simp only [Set.mem_union, Set.mem_compl_iff, not_or, not_not, Y₁, Y₂] at hc
      exact hU₁₂ ⟨hz, hW₁.2.2 hc.1, hW₂.2.2 hc.2⟩
    have : Z ∩ ⋂₀ ((A₁ \ {Y₁}) ∪ (A₂ \ {Y₂})) = ∅ := by
      grind
    rw [← Set.not_nonempty_iff_eq_empty] at this
    have H' : ∀ A : Set (Set X), A ⊆ {U | IsOpen U ∧ IsCompact U} → A.Finite → IsCompact (⋂₀ A) := by
      intro A hA hA_fin
      induction h_card : A.ncard generalizing A with
      | zero =>
        simp_all only [Set.mem_setOf_eq, Set.subset_empty_iff, Set.ncard_eq_zero, Set.sInter_empty,
          Set.empty_subset, Set.finite_empty]
        exact CompactSpace.isCompact_univ
      | succ n ih =>
        have : Finite A := hA_fin
        rw [Set.ncard_eq_succ] at h_card
        rcases h_card with ⟨S, A, hSA, rfl, h_card⟩
        simp only [Set.sInter_insert]
        specialize ih A ((Set.subset_insert S A).trans hA) (by apply hA_fin.subset (Set.subset_insert S A)) h_card
        have := hA (Set.mem_insert S A)
        refine QuasiSeparatedSpace.inter_isCompact _ _ this.1 this.2 ?_ ih
        apply Set.Finite.isOpen_sInter
        · apply hA_fin.subset
          grind
        · grind
    have H : ∀ A, A ⊆ B → A.Finite → IsCompact (⋂₀ A) := by
      intro A hA hA_fin
      let Ao := {U | U ∈ A ∧ IsOpen U}
      let Ac := {Z | Z ∈ A ∧ IsClosed Z}
      have hAoc : Ao ∪ Ac = A := by
        apply subset_antisymm
        · grind
        · intro x hxA
          have : x ∈ 𝔅 := hB𝒮.1 (hA hxA)
          apply this.imp <;> grind
      rw [← hAoc, Set.sInter_union]
      refine IsCompact.inter_right (H' Ao ?_ (hA_fin.subset (by grind))) (isClosed_sInter (by grind))
      intro s hs
      have h𝔅_cmpt : ∀ s ∈ 𝔅, IsCompact s := by
        rintro s (hs|hs)
        · exact hs.2
        · exact hs.1.isCompact
      refine ⟨hs.2, h𝔅_cmpt _ ?_⟩
      grind
    suffices ∀ A, A ⊆ B → A.Finite → (Z ∩ ⋂₀ A).Nonempty by
      specialize this ((A₁ \ {Y₁}) ∪ (A₂ \ {Y₂}))
        (by simp only [Set.union_subset_iff]; grind)
        (hA₁'.diff.union hA₂'.diff)
      contradiction
    intro A hA hA_fin
    dsimp [Z]
    rw [Set.sInter_eq_iInter, Set.inter_comm]
    apply (H A hA hA_fin).inter_iInter_nonempty
    · exact fun b ↦ b.2.2
    · intro F
      have := hB𝒮.2.1 (A ∪ (by classical exact (F.image Subtype.val : Set (Set X))))
      specialize this (by simp only [Finset.coe_image, Set.union_subset_iff, Set.image_subset_iff]; grind)
      specialize this (by simp only [Finset.coe_image, Set.finite_union, hA_fin, true_and]; exact Set.toFinite (Subtype.val '' ↑F))
      convert this
      ext
      simp only [Set.iInter_coe_set, Set.mem_inter_iff, Set.mem_sInter, Set.mem_iInter,
        Finset.coe_image, Set.mem_union, Set.mem_image, Finset.mem_coe, Subtype.exists,
        exists_and_right, exists_eq_right]
      grind

/-- If `s` is closed in the constructible topology and `x` is in the closure of `s`, then
it is the specialization of a point in `s`. -/
@[stacks 0903 "(1)"]
lemma exists_specializes_of_isClosed_constructibleTopology_of_mem_closure [SpectralSpace X]
    {s : Set X} (hs : IsClosed[constructibleTopology X] s) {x : X} (hx : x ∈ closure s) :
    ∃ y ∈ s, y ⤳ x := by
  -- Strategy: For each compact open U ∋ x, U ∩ s is closed in the constructible topology
  -- and nonempty. By compactness of WithConstructibleTopology X, the total intersection
  -- is nonempty. Any point in the intersection specializes to x.
  --
  -- Compact opens are clopen in the constructible topology
  have hU_closed_constr : ∀ (U : Set X), IsOpen U → IsCompact U →
      @IsClosed (WithConstructibleTopology X) _ U := by
    intro U hUo hUc
    rw [← @isOpen_compl_iff (WithConstructibleTopology X)]
    show @IsOpen (WithConstructibleTopology X) _ Uᶜ
    have h1 : IsClosed Uᶜ := hUo.isClosed_compl
    have h2 : IsCompact Uᶜᶜ := by rwa [compl_compl]
    exact h2.isOpen_constructibleTopology_of_isClosed h1
  -- Define the family indexed by compact opens containing x
  let ι := { U : Set X // IsOpen U ∧ IsCompact U ∧ x ∈ U }
  -- Each U_i ∩ s is closed in the constructible topology
  have hF_closed : ∀ i : ι, @IsClosed (WithConstructibleTopology X) _
      ((i : Set X) ∩ s) := by
    rintro ⟨U, hUo, hUc, _⟩
    exact (hU_closed_constr U hUo hUc).inter hs
  -- Total intersection is nonempty by compactness + FIP
  have h_inter : (⋂ i : ι, ((i : Set X) ∩ s)).Nonempty := by
    have := @CompactSpace.iInter_nonempty (WithConstructibleTopology X) _
      compactSpace_withConstructibleTopology (ι := ι) (t := fun i => (i : Set X) ∩ s)
      hF_closed
    apply this; clear this
    intro T
    -- ⋂ i ∈ T, (U_i ∩ s) ⊇ (⋂ i ∈ T, U_i) ∩ s
    -- Need: (⋂ j ∈ T, ((j : Set X) ∩ s)).Nonempty
    -- This follows from: (⋂ j ∈ T, (j : Set X)) ∩ s is nonempty
    -- and ⋂ j ∈ T, ((j : Set X) ∩ s) ⊇ (⋂ j ∈ T, (j : Set X)) ∩ s
    have hopen : IsOpen (⋂ j ∈ T, (j : Set X)) :=
      Set.Finite.isOpen_biInter T.finite_toSet fun j _ => j.2.1
    have hmem : x ∈ ⋂ j ∈ T, (j : Set X) :=
      Set.mem_biInter fun j _ => j.2.2.2
    have hne := mem_closure_iff_nhds.mp hx _ (hopen.mem_nhds hmem)
    obtain ⟨y, hy⟩ := hne
    refine ⟨y, ?_⟩
    rw [Set.mem_iInter]
    intro j
    rw [Set.mem_iInter]
    intro hj
    exact Set.mem_inter ((Set.mem_iInter₂.mp hy.1) j hj) hy.2
  -- Extract point and verify properties
  obtain ⟨y, hy⟩ := h_inter
  rw [Set.mem_iInter] at hy
  refine ⟨y, ?_, ?_⟩
  · -- y ∈ s
    exact (hy ⟨Set.univ, isOpen_univ, CompactSpace.isCompact_univ, Set.mem_univ x⟩).2
  · -- y ⤳ x
    rw [specializes_iff_forall_open]
    intro U hUo hxU
    obtain ⟨W, ⟨hWo, hWc⟩, hxW, hWU⟩ :=
      PrespectralSpace.isTopologicalBasis.exists_subset_of_mem_open hxU hUo
    exact hWU (hy ⟨W, hWo, hWc, hxW⟩).1

/-- If `s` is closed in the constructible topology and stable under specialization, it is closed. -/
@[stacks 0903 "(2)"]
lemma IsClosed.of_isClosed_constructibleTopology [SpectralSpace X] {s : Set X}
    (hs : IsClosed[constructibleTopology X] s) (h : StableUnderSpecialization s) :
    IsClosed s := by
  rw [← closure_subset_iff_isClosed]
  intro x hx
  obtain ⟨y, hy, hx⟩ :=
    exists_specializes_of_isClosed_constructibleTopology_of_mem_closure hs hx
  exact h hx hy

private lemma SpectralSpace.totallySeparatedSpace_of_isClosed_singleton [SpectralSpace X]
    (h : ∀ x : X, IsClosed ({x} : Set X)) : TotallySeparatedSpace X := by
  -- When all singletons are closed, specialization is trivial.
  have spec_triv : ∀ x y : X, x ⤳ y → x = y := by
    intro x y hxy
    rw [specializes_iff_mem_closure] at hxy
    rwa [(h x).closure_eq, Set.mem_singleton_iff, eq_comm] at hxy
  -- Every set is stable under specialization.
  have stable : ∀ s : Set X, StableUnderSpecialization s := by
    intro s x y hxy hx
    rwa [← spec_triv _ _ hxy]
  -- Every compact open is clopen: it's constructibly closed and specialization-stable,
  -- hence closed by `IsClosed.of_isClosed_constructibleTopology`.
  have clopen : ∀ U : Set X, IsOpen U → IsCompact U → IsClopen U := by
    intro U hUo hUc
    refine ⟨?_, hUo⟩
    exact IsClosed.of_isClosed_constructibleTopology
      (@IsClosed.mk X (constructibleTopology X) U
        (IsCompact.isOpen_constructibleTopology_of_isClosed
          (by rwa [compl_compl] : IsCompact Uᶜᶜ) hUo.isClosed_compl))
      (stable U)
  -- Use compact open basis to separate points.
  rw [totallySeparatedSpace_iff_exists_isClopen]
  intro x y hxy
  -- Since {y} is closed and x ∉ {y}, x is in the open set {y}ᶜ.
  have hx_notin : x ∉ ({y} : Set X) := by simp [hxy]
  have hopen : IsOpen ({y} : Set X)ᶜ := (h y).isOpen_compl
  have hx_mem : x ∈ ({y} : Set X)ᶜ := hx_notin
  -- Find a compact open W with x ∈ W ⊆ {y}ᶜ
  obtain ⟨W, ⟨hWo, hWc⟩, hxW, hWU⟩ :=
    PrespectralSpace.isTopologicalBasis.exists_subset_of_mem_open hx_mem hopen
  exact ⟨W, clopen W hWo hWc, hxW, by simp [Set.mem_compl_iff]; exact fun h => hWU h (Set.mem_singleton y)⟩

@[stacks 0905 "(6) → (1)"]
theorem SpectralSpace.t2Space_of_isClosed_singleton [SpectralSpace X]
    (h : ∀ x : X, IsClosed ({x} : Set X)) : T2Space X :=
  letI := SpectralSpace.totallySeparatedSpace_of_isClosed_singleton h
  inferInstance

@[stacks 0905 "(6) → (1)"]
theorem SpectralSpace.totallyDisconnectedSpace_of_isClosed_singleton [SpectralSpace X]
    (h : ∀ x : X, IsClosed ({x} : Set X)) : TotallyDisconnectedSpace X :=
  letI := SpectralSpace.totallySeparatedSpace_of_isClosed_singleton h
  inferInstance
-- use `isTotallyDisconnected_of_isClopen_set`
-- use `exists_specializes_of_isClosed_constructibleTopology_of_mem_closure,
-- IsClosed.of_isClosed_constructibleTopology`
