/-
Copyright (c) 2025 Jiedong Jiang, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiedong Jiang, Christian Merten
-/
import Proetale.Mathlib.Topology.Inseparable
import Mathlib.Topology.Spectral.Basic
import Mathlib.Topology.Spectral.ConstructibleTopology
import Mathlib.Topology.JacobsonSpace
import Mathlib.Data.Set.Card

/-!
# Constructible topology

In this file we define the constructible topology on a topological space. This is the topology
generated by compact open subsets and their complements.
-/

variable {X : Type*} [TopologicalSpace X]

open Topology

/-- If `s` is closed in the constructible topology and `x` is in the closure of `s`, then
it is the specialization of a point in `s`. -/
@[stacks 0903 "(1)"]
lemma exists_specializes_of_isClosed_constructibleTopology_of_mem_closure [SpectralSpace X]
    {s : Set X} (hs : IsClosed[constructibleTopology X] s) {x : X} (hx : x ∈ closure s) :
    ∃ y ∈ s, y ⤳ x :=
  sorry

/-- If `s` is closed in the constructible topology and stable under specialization, it is closed. -/
@[stacks 0903 "(2)"]
lemma IsClosed.of_isClosed_constructibleTopology [SpectralSpace X] {s : Set X}
    (hs : IsClosed[constructibleTopology X] s) (h : StableUnderSpecialization s) :
    IsClosed s := by
  rw [← closure_subset_iff_isClosed]
  intro x hx
  obtain ⟨y, hy, hx⟩ :=
    exists_specializes_of_isClosed_constructibleTopology_of_mem_closure hs hx
  exact h hx hy

@[stacks 0905 "(6) → (1)"]
theorem SpectralSpace.t2Space_of_isClosed_singleton [SpectralSpace X]
    (h : ∀ x : X, IsClosed ({x} : Set X)) : T2Space X :=
  sorry

@[stacks 0905 "(6) → (1)"]
theorem SpectralSpace.totallyDisconnectedSpace_of_isClosed_singleton [SpectralSpace X]
    (h : ∀ x : X, IsClosed ({x} : Set X)) : TotallyDisconnectedSpace X :=
  sorry
-- use `isTotallyDisconnected_of_isClopen_set`
-- use `exists_specializes_of_isClosed_constructibleTopology_of_mem_closure,
-- IsClosed.of_isClosed_constructibleTopology`
