/-
Copyright (c) 2025 Jiedong Jiang, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiedong Jiang, Christian Merten
-/
import Mathlib

/-!
# Étale morphisms from flatness and unramifiedness

A finitely presented morphism that is flat and formally unramified is étale, both at the
level of local rings and at the level of schemes.
-/

universe u

open CategoryTheory Limits MorphismProperty Algebra IsLocalRing

variable (R : Type*) {S : Type*} [CommRing R] [CommRing S] [Algebra R S]

/-- A flat, finitely presented `R`-algebra `S` is étale at a prime `q` of `S` over a prime `p`
of `R` whenever the residue field extension is separable and the maximal ideal of the
localization of `S` at `q` is generated by the image of `p`. -/
@[stacks 00TF]
lemma Algebra.isEtaleAt_of_flat_of_unramified [FinitePresentation R S]
    (p : Ideal R) [p.IsPrime] (q : Ideal S) [q.IsPrime] [q.LiesOver p]
    [Module.Flat (Localization.AtPrime p) (Localization.AtPrime q)]
    (hr : Algebra.IsSeparable p.ResidueField q.ResidueField)
    (hpq : p.map (algebraMap R (Localization.AtPrime q)) = maximalIdeal _) :
    Algebra.IsEtaleAt R q := by
  have : EssFiniteType (Localization.AtPrime p) (Localization.AtPrime q) := .of_comp R _ _
  sorry

namespace AlgebraicGeometry

/-- A flat, locally finitely presented and formally unramified morphism of schemes is étale. -/
theorem Etale.of_flat_of_locallyOfFinitePresentation_of_formallyUnramified {X Y : Scheme.{u}}
    (f : X ⟶ Y) [Flat f] [LocallyOfFinitePresentation f] [FormallyUnramified f] : Etale f := by
  sorry

end AlgebraicGeometry
