/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Mathlib.Algebra.Category.Grp.Abelian
import Mathlib.Algebra.Category.Grp.Adjunctions
import Mathlib.Algebra.Category.Grp.Colimits
import Mathlib.Algebra.Category.Grp.FilteredColimits
import Mathlib.Algebra.Category.Grp.Limits
import Mathlib.AlgebraicTopology.ExtraDegeneracy
import Mathlib.AlgebraicTopology.AlternatingFaceMapComplex
import Mathlib.CategoryTheory.Sites.Abelian
import Mathlib.CategoryTheory.Sites.LeftExact
import Mathlib.CategoryTheory.Sites.LocallyBijective
import Proetale.Mathlib.CategoryTheory.Sites.SheafCohomology.FreeAbelianSheaf

/-!
# The Čech resolution of a free abelian sheaf

Let `(C, J)` be a site with pullbacks and let `f : V ⟶ U` be a morphism generating
a covering sieve of `U`. We construct the Čech complex of free abelian sheaves

`⋯ ⟶ ℤ[V ×_U V] ⟶ ℤ[V] ⟶ ℤ[U] ⟶ 0`

associated to the Čech nerve of `f` and show that it is a resolution of the free
abelian sheaf `ℤ[U]`: the augmentation is an epimorphism and the complex is exact.

This is the key input for comparing Čech cohomology with derived functor cohomology
(Cartan's criterion).
-/

universe u

open CategoryTheory Limits Opposite AlgebraicTopology
open scoped Simplicial

namespace CategoryTheory

variable {C : Type (u + 1)} [Category.{u} C] [HasFiniteWidePullbacks C]
variable (J : GrothendieckTopology C) [HasWeakSheafify J AddCommGrpCat.{u + 1}]

/-- The free abelian presheaf functor, sending `U : C` to the free abelian group
presheaf on the (universe-lifted) presheaf represented by `U`. -/
noncomputable def freeAbelianPresheafFunctor : C ⥤ (Cᵒᵖ ⥤ AddCommGrpCat.{u + 1}) :=
  uliftYoneda.{u + 1} ⋙ (Functor.whiskeringRight _ _ _).obj AddCommGrpCat.free

variable {U V : C} (f : V ⟶ U) {W : C}

/-- The Čech complex of free abelian presheaves associated to `f : V ⟶ U`:
in degree `n` it is the free abelian presheaf on the `(n+1)`-fold fibre product
`V ×_U ⋯ ×_U V`, with the alternating sums of the face maps as differentials. -/
noncomputable def cechFreePresheafComplex : ChainComplex (Cᵒᵖ ⥤ AddCommGrpCat.{u + 1}) ℕ :=
  AlternatingFaceMapComplex.obj
    (((SimplicialObject.whiskering _ _).obj (freeAbelianPresheafFunctor)).obj
      (Arrow.mk f).cechNerve)

/-- The Čech complex of free abelian sheaves associated to `f : V ⟶ U`. -/
noncomputable def cechFreeComplex : ChainComplex (Sheaf J AddCommGrpCat.{u + 1}) ℕ :=
  ((presheafToSheaf J _).mapHomologicalComplex _).obj (cechFreePresheafComplex f)

/-- The degree `n` part of the Čech complex of free abelian sheaves: the free
abelian sheaf on the `(n+1)`-fold fibre product of `V` over `U`. -/
noncomputable def cechFree (n : ℕ) : Sheaf J AddCommGrpCat.{u + 1} :=
  (cechFreeComplex J f).X n

lemma cechFree_eq (n : ℕ) :
    cechFree J f n =
      (freeAbelianSheafFunctor J).obj ((Arrow.mk f).cechNerve.obj (op ⦋n⦌)) :=
  rfl

/-- The differential of the Čech complex of free abelian sheaves. -/
noncomputable def cechFreeD (n : ℕ) : cechFree J f (n + 1) ⟶ cechFree J f n :=
  (cechFreeComplex J f).d (n + 1) n

theorem cechFreeD_comp_d (n : ℕ) : cechFreeD J f (n + 1) ≫ cechFreeD J f n = 0 :=
  (cechFreeComplex J f).d_comp_d _ _ _

/-- The augmentation of the Čech complex of free abelian sheaves. -/
noncomputable def cechFreeAug : cechFree J f 0 ⟶ (freeAbelianSheafFunctor J).obj U :=
  (freeAbelianSheafFunctor J).map ((Arrow.mk f).augmentedCechNerve.hom.app (op ⦋0⦌))

/-! ### Auxiliary constructions

To prove that the Čech complex is a resolution, we factor the augmentation through the
free abelian presheaf on the sieve generated by `f`. The resulting augmented complex of
presheaves is, evaluated at any `W : C`, the free abelian Čech complex of the *surjective*
map of types `(W ⟶ V) → {g : W ⟶ U // g factors through f}`. The Čech nerve of a
surjection of types has an extra degeneracy, so these evaluations are exact; exactness of
the sheafified complex follows since sheafification is exact. Finally, the inclusion of the
sieve into `yoneda U` becomes an isomorphism after taking free abelian presheaves and
sheafifying, because the sieve is covering. -/

section Resolution

variable {f}

omit [HasFiniteWidePullbacks C] in
lemma exists_comp_eq_of_generate_singleton {W : C} {g : W ⟶ U}
    (hg : Sieve.generate (Presieve.singleton f) g) : ∃ h : W ⟶ V, h ≫ f = g := by
  obtain ⟨Y, h, l, hl, rfl⟩ := hg
  cases hl
  exact ⟨h, rfl⟩

variable (f)

/-- A choice of a factorization through `f` of a morphism in the sieve generated by `f`. -/
noncomputable def cechSplitting {W : C} {g : W ⟶ U}
    (hg : Sieve.generate (Presieve.singleton f) g) : W ⟶ V :=
  (exists_comp_eq_of_generate_singleton hg).choose

omit [HasFiniteWidePullbacks C] in
@[reassoc (attr := simp)]
lemma cechSplitting_comp {W : C} {g : W ⟶ U}
    (hg : Sieve.generate (Presieve.singleton f) g) : cechSplitting f hg ≫ f = g :=
  (exists_comp_eq_of_generate_singleton hg).choose_spec

omit [HasFiniteWidePullbacks C] in
lemma generate_singleton_of_comp {W : C} (h : W ⟶ V) (g : W ⟶ U) (hh : h ≫ f = g) :
    Sieve.generate (Presieve.singleton f) g :=
  ⟨V, h, f, Presieve.singleton.mk, hh⟩

lemma comp_base_mem_generate_singleton {W : C} {m : SimplexCategoryᵒᵖ}
    (x : W ⟶ (Arrow.mk f).cechNerve.obj m) :
    Sieve.generate (Presieve.singleton f) (x ≫ WidePullback.base _) :=
  generate_singleton_of_comp f (x ≫ WidePullback.π _ 0) _ (by simp)

@[reassoc (attr := simp)]
lemma cechNerve_π_comp {m : SimplexCategoryᵒᵖ} (i : Fin (m.unop.len + 1)) :
    WidePullback.π (fun _ : Fin (m.unop.len + 1) => (Arrow.mk f).hom) i ≫ f =
      WidePullback.base (fun _ : Fin (m.unop.len + 1) => (Arrow.mk f).hom) :=
  WidePullback.π_arrow _ i

@[reassoc (attr := simp)]
lemma cechNerve_map_comp_base {D : Type*} [Category D] {X Y : D} (g : X ⟶ Y)
    [∀ n : ℕ, HasWidePullback (Arrow.mk g).right
      (fun _ : Fin (n + 1) => (Arrow.mk g).left) fun _ => (Arrow.mk g).hom]
    {m m' : SimplexCategoryᵒᵖ} (θ : m ⟶ m') :
    (Arrow.mk g).cechNerve.map θ ≫ WidePullback.base _ = WidePullback.base _ := by
  dsimp [Arrow.cechNerve]
  rw [WidePullback.lift_base]

@[reassoc (attr := simp)]
lemma cechNerve_map_comp_π {D : Type*} [Category D] {X Y : D} (g : X ⟶ Y)
    [∀ n : ℕ, HasWidePullback (Arrow.mk g).right
      (fun _ : Fin (n + 1) => (Arrow.mk g).left) fun _ => (Arrow.mk g).hom]
    {m m' : SimplexCategoryᵒᵖ} (θ : m ⟶ m') (j : Fin (m'.unop.len + 1)) :
    (Arrow.mk g).cechNerve.map θ ≫ WidePullback.π _ j =
      WidePullback.π _ (θ.unop.toOrderHom j) := by
  dsimp [Arrow.cechNerve]
  rw [WidePullback.lift_π]

/-- The augmentation of the Čech nerve of `f`, corestricted to the sieve generated
by `f`, as a morphism of presheaves of types. -/
@[simps]
noncomputable def cechNerveToSieve (m : SimplexCategoryᵒᵖ) :
    uliftYoneda.{u + 1}.obj ((Arrow.mk f).cechNerve.obj m) ⟶
      Sieve.uliftFunctor.{u + 1} (Sieve.generate (Presieve.singleton f)) where
  app W := ↾fun x =>
    ULift.up ⟨x.down ≫ WidePullback.base _, comp_base_mem_generate_singleton f x.down⟩
  naturality W W' h := by
    apply ConcreteCategory.hom_ext
    intro x
    exact congrArg ULift.up (Subtype.ext (Category.assoc _ _ _))

lemma cechNerveToSieve_comp_inclusion (m : SimplexCategoryᵒᵖ) :
    cechNerveToSieve f m ≫
      Sieve.uliftFunctorInclusion.{u + 1} (Sieve.generate (Presieve.singleton f)) =
      uliftYoneda.{u + 1}.map (WidePullback.base _) :=
  rfl

/-- The free abelian presheaf version of the corestricted augmentation in degree zero. -/
noncomputable def cechFreeToSieve :
    freeAbelianPresheafFunctor.obj ((Arrow.mk f).cechNerve.obj (op ⦋0⦌)) ⟶
      Sieve.uliftFunctor.{u + 1} (Sieve.generate (Presieve.singleton f)) ⋙ AddCommGrpCat.free :=
  Functor.whiskerRight (cechNerveToSieve f (op ⦋0⦌)) AddCommGrpCat.free

/-- The factorization of the free presheaf augmentation through the free abelian
presheaf on the sieve generated by `f`. -/
lemma freeAbelianPresheafFunctor_map_aug_fac :
    freeAbelianPresheafFunctor.map ((Arrow.mk f).augmentedCechNerve.hom.app (op ⦋0⦌)) =
      cechFreeToSieve f ≫
        Functor.whiskerRight
          (Sieve.uliftFunctorInclusion.{u + 1} (Sieve.generate (Presieve.singleton f)))
          AddCommGrpCat.free := by
  have h : freeAbelianPresheafFunctor.map ((Arrow.mk f).augmentedCechNerve.hom.app (op ⦋0⦌)) =
      ((Functor.whiskeringRight Cᵒᵖ _ _).obj AddCommGrpCat.free).map
        (cechNerveToSieve f (op ⦋0⦌) ≫
          Sieve.uliftFunctorInclusion.{u + 1} (Sieve.generate (Presieve.singleton f))) := by
    rw [cechNerveToSieve_comp_inclusion]
    rfl
  rw [h, Functor.map_comp]
  rfl

section Evaluation

variable (W)

/-- The augmented Čech nerve of `f` evaluated at `W : C`, augmented over the sections
over `W` of the sieve generated by `f`. -/
@[simps]
noncomputable def cechNerveEvalAug : SimplicialObject.Augmented (Type (u + 1)) where
  left := (Arrow.mk f).cechNerve ⋙ uliftYoneda.{u + 1} ⋙
    (evaluation Cᵒᵖ (Type (u + 1))).obj (op W)
  right := (Sieve.uliftFunctor.{u + 1} (Sieve.generate (Presieve.singleton f))).obj (op W)
  hom :=
    { app := fun m => (cechNerveToSieve f m).app (op W)
      naturality := fun m m' θ => by
        apply ConcreteCategory.hom_ext
        intro x
        refine congrArg ULift.up (Subtype.ext ?_)
        exact (Category.assoc _ _ _).trans (by rw [cechNerve_map_comp_base f θ]) }

/-- The evaluation at `W` of the degree zero augmentation, as a map of types
to the sections of the sieve generated by `f`. -/
noncomputable def cechToSieveSections : ULift.{u + 1} (W ⟶ V) ⟶
    (Sieve.uliftFunctor.{u + 1} (Sieve.generate (Presieve.singleton f))).obj (op W) :=
  ↾fun x => ULift.up ⟨x.down ≫ f, generate_singleton_of_comp f x.down _ rfl⟩

/-- Since every morphism in the sieve generated by `f` factors through `f`,
the corestricted evaluation map is a split epimorphism (of types). -/
noncomputable def cechToSieveSectionsSplitEpi :
    SplitEpi (Arrow.mk (cechToSieveSections f W)).hom where
  section_ := ↾fun g => ULift.up (cechSplitting f g.down.2)
  id := by
    apply ConcreteCategory.hom_ext
    intro g
    exact congrArg ULift.up (Subtype.ext (cechSplitting_comp f g.down.2))

/-- Comparison map from the Čech nerve (in types) of the corestricted evaluation map
to the evaluation at `W` of the Čech nerve of `f`. -/
noncomputable def cechNerveEvalCompare (m : SimplexCategoryᵒᵖ) :
    (Arrow.mk (cechToSieveSections f W)).cechNerve.obj m ⟶
      ULift.{u + 1} (W ⟶ (Arrow.mk f).cechNerve.obj m) :=
  ↾fun y => ULift.up (WidePullback.lift
    ((WidePullback.base (fun _ : Fin (m.unop.len + 1) =>
      (Arrow.mk (cechToSieveSections f W)).hom) y).down.1)
    (fun i => (WidePullback.π (fun _ : Fin (m.unop.len + 1) =>
      (Arrow.mk (cechToSieveSections f W)).hom) i y).down)
    (fun i => by
      have h := ConcreteCategory.congr_hom (WidePullback.π_arrow
        (fun _ : Fin (m.unop.len + 1) => (Arrow.mk (cechToSieveSections f W)).hom) i) y
      exact congrArg (fun t => t.down.1) h))

/-- Inverse of `cechNerveEvalCompare`. -/
noncomputable def cechNerveEvalCompareInv (m : SimplexCategoryᵒᵖ) :
    ULift.{u + 1} (W ⟶ (Arrow.mk f).cechNerve.obj m) ⟶
      (Arrow.mk (cechToSieveSections f W)).cechNerve.obj m :=
  WidePullback.lift ((cechNerveToSieve f m).app (op W))
    (fun i => ↾fun x => ULift.up (x.down ≫ WidePullback.π _ i))
    (fun i => by
      apply ConcreteCategory.hom_ext
      intro x
      exact congrArg ULift.up (Subtype.ext
        ((Category.assoc _ _ _).trans (by rw [cechNerve_π_comp]))))

@[simp]
lemma cechNerveEvalCompare_down_π (m : SimplexCategoryᵒᵖ)
    (y : (Arrow.mk (cechToSieveSections f W)).cechNerve.obj m) (i : Fin (m.unop.len + 1)) :
    (cechNerveEvalCompare f W m y).down ≫ WidePullback.π _ i =
      (WidePullback.π (fun _ : Fin (m.unop.len + 1) =>
        (Arrow.mk (cechToSieveSections f W)).hom) i y).down :=
  WidePullback.lift_π _ _ _ _ i

@[simp]
lemma cechNerveEvalCompare_down_base (m : SimplexCategoryᵒᵖ)
    (y : (Arrow.mk (cechToSieveSections f W)).cechNerve.obj m) :
    (cechNerveEvalCompare f W m y).down ≫ WidePullback.base _ =
      (WidePullback.base (fun _ : Fin (m.unop.len + 1) =>
        (Arrow.mk (cechToSieveSections f W)).hom) y).down.1 :=
  WidePullback.lift_base _ _ _ _

@[simp]
lemma π_cechNerveEvalCompareInv (m : SimplexCategoryᵒᵖ)
    (x : ULift.{u + 1} (W ⟶ (Arrow.mk f).cechNerve.obj m)) (i : Fin (m.unop.len + 1)) :
    WidePullback.π (fun _ : Fin (m.unop.len + 1) =>
        (Arrow.mk (cechToSieveSections f W)).hom) i (cechNerveEvalCompareInv f W m x) =
      ULift.up (x.down ≫ WidePullback.π _ i) := by
  have h := WidePullback.lift_π (arrows := fun _ : Fin (m.unop.len + 1) =>
    (Arrow.mk (cechToSieveSections f W)).hom) ((cechNerveToSieve f m).app (op W))
    (fun i => ↾fun x => ULift.up (x.down ≫ WidePullback.π _ i))
    (fun i => by
      apply ConcreteCategory.hom_ext
      intro x
      exact congrArg ULift.up (Subtype.ext
        ((Category.assoc _ _ _).trans (by rw [cechNerve_π_comp])))) i
  exact ConcreteCategory.congr_hom h x

@[simp]
lemma base_cechNerveEvalCompareInv (m : SimplexCategoryᵒᵖ)
    (x : ULift.{u + 1} (W ⟶ (Arrow.mk f).cechNerve.obj m)) :
    WidePullback.base (fun _ : Fin (m.unop.len + 1) =>
        (Arrow.mk (cechToSieveSections f W)).hom) (cechNerveEvalCompareInv f W m x) =
      (cechNerveToSieve f m).app (op W) x := by
  have h := WidePullback.lift_base (arrows := fun _ : Fin (m.unop.len + 1) =>
    (Arrow.mk (cechToSieveSections f W)).hom) ((cechNerveToSieve f m).app (op W))
    (fun i => ↾fun x => ULift.up (x.down ≫ WidePullback.π _ i))
    (fun i => by
      apply ConcreteCategory.hom_ext
      intro x
      exact congrArg ULift.up (Subtype.ext
        ((Category.assoc _ _ _).trans (by rw [cechNerve_π_comp]))))
  exact ConcreteCategory.congr_hom h x

/-- The augmented Čech nerve (in types) of the corestricted evaluation map is
isomorphic to the evaluation at `W` of the augmented Čech nerve of `f`,
augmented over the sieve sections. -/
noncomputable def cechNerveEvalAugIso :
    (Arrow.mk (cechToSieveSections f W)).augmentedCechNerve ≅ cechNerveEvalAug f W :=
  Comma.isoMk
    (NatIso.ofComponents
      (fun m => ⟨cechNerveEvalCompare f W m, cechNerveEvalCompareInv f W m,
        by
          apply ConcreteCategory.hom_ext
          intro y
          rw [types_comp_apply, types_id_apply]
          apply Types.limit_ext
          rintro (_ | i)
          · exact (base_cechNerveEvalCompareInv f W m _).trans
              (congrArg ULift.up (Subtype.ext (cechNerveEvalCompare_down_base f W m y)))
          · exact (π_cechNerveEvalCompareInv f W m _ i).trans
              (congrArg ULift.up (cechNerveEvalCompare_down_π f W m y i)),
        by
          apply ConcreteCategory.hom_ext
          intro x
          rw [types_comp_apply, types_id_apply]
          refine ULift.ext _ _ ?_
          apply WidePullback.hom_ext
          · intro j
            exact (cechNerveEvalCompare_down_π f W m _ j).trans
              (congrArg ULift.down (π_cechNerveEvalCompareInv f W m x j))
          · exact (cechNerveEvalCompare_down_base f W m _).trans
              (congrArg (fun t => t.down.1) (base_cechNerveEvalCompareInv f W m x))⟩)
      (fun {m m'} θ => by
        apply ConcreteCategory.hom_ext
        intro y
        rw [types_comp_apply, types_comp_apply]
        refine ULift.ext _ _ ?_
        apply WidePullback.hom_ext
        · intro j
          have h1 : WidePullback.π (fun _ : Fin (m'.unop.len + 1) =>
              (Arrow.mk (cechToSieveSections f W)).hom) j
                ((Arrow.mk (cechToSieveSections f W)).cechNerve.map θ y) =
              WidePullback.π (fun _ : Fin (m.unop.len + 1) =>
                (Arrow.mk (cechToSieveSections f W)).hom) (θ.unop.toOrderHom j) y :=
            ConcreteCategory.congr_hom (cechNerve_map_comp_π (cechToSieveSections f W) θ j) y
          have hD : (cechNerveEvalCompare f W m y).down ≫
                WidePullback.π (fun _ : Fin (m.unop.len + 1) => (Arrow.mk f).hom)
                  (θ.unop.toOrderHom j) =
              ((cechNerveEvalCompare f W m y).down ≫ (Arrow.mk f).cechNerve.map θ) ≫
                WidePullback.π (fun _ : Fin (m'.unop.len + 1) => (Arrow.mk f).hom) j := by
            rw [Category.assoc, cechNerve_map_comp_π f θ j]
          exact ((cechNerveEvalCompare_down_π f W m' _ j).trans
            ((congrArg ULift.down h1).trans
              (cechNerveEvalCompare_down_π f W m y (θ.unop.toOrderHom j)).symm)).trans hD
        · have h1 : WidePullback.base (fun _ : Fin (m'.unop.len + 1) =>
              (Arrow.mk (cechToSieveSections f W)).hom)
                ((Arrow.mk (cechToSieveSections f W)).cechNerve.map θ y) =
              WidePullback.base (fun _ : Fin (m.unop.len + 1) =>
                (Arrow.mk (cechToSieveSections f W)).hom) y :=
            ConcreteCategory.congr_hom (cechNerve_map_comp_base (cechToSieveSections f W) θ) y
          have hD : (cechNerveEvalCompare f W m y).down ≫
                WidePullback.base (fun _ : Fin (m.unop.len + 1) => (Arrow.mk f).hom) =
              ((cechNerveEvalCompare f W m y).down ≫ (Arrow.mk f).cechNerve.map θ) ≫
                WidePullback.base (fun _ : Fin (m'.unop.len + 1) => (Arrow.mk f).hom) := by
            rw [Category.assoc, cechNerve_map_comp_base f θ]
          exact ((cechNerveEvalCompare_down_base f W m' _).trans
            ((congrArg (fun t => t.down.1) h1).trans
              (cechNerveEvalCompare_down_base f W m y).symm)).trans hD))
    (Iso.refl _)
    (by
      ext m : 2
      apply DFunLike.ext
      intro y
      exact congrArg ULift.up (Subtype.ext (cechNerveEvalCompare_down_base f W m y)))

/-- The evaluation at `W` of the augmented Čech nerve of `f`, augmented over the
sieve sections, admits an extra degeneracy. -/
noncomputable def cechNerveEvalED :
    SimplicialObject.Augmented.ExtraDegeneracy (cechNerveEvalAug f W) :=
  SimplicialObject.Augmented.ExtraDegeneracy.ofIso (cechNerveEvalAugIso f W)
    (Arrow.AugmentedCechNerve.extraDegeneracy _ (cechToSieveSectionsSplitEpi f W))

/-- The evaluation at `W` of the Čech complex of free abelian presheaves. -/
noncomputable abbrev cechFreeEvalComplex : ChainComplex AddCommGrpCat.{u + 1} ℕ :=
  AlternatingFaceMapComplex.obj (SimplicialObject.Augmented.drop.obj
    (((SimplicialObject.Augmented.whiskering _ _).obj AddCommGrpCat.free).obj
      (cechNerveEvalAug f W)))

/-- The evaluation at `W` of the Čech complex of free abelian presheaves is homotopy
equivalent to the free abelian group on the sieve sections, in degree zero. -/
noncomputable def cechFreeEvalHomotopyEquiv :
    HomotopyEquiv (cechFreeEvalComplex f W)
      ((ChainComplex.single₀ _).obj (AddCommGrpCat.free.obj
        ((Sieve.uliftFunctor.{u + 1} (Sieve.generate (Presieve.singleton f))).obj (op W)))) :=
  ((cechNerveEvalED f W).map AddCommGrpCat.free).homotopyEquiv

lemma cechFreePresheafComplex_d_app (n : ℕ) :
    ((cechFreePresheafComplex f).d (n + 1) n).app (op W) =
      (cechFreeEvalComplex f W).d (n + 1) n := by
  dsimp only [cechFreePresheafComplex, cechFreeEvalComplex]
  rw [AlternatingFaceMapComplex.obj_d_eq, AlternatingFaceMapComplex.obj_d_eq,
    NatTrans.app_sum]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [NatTrans.app_zsmul]
  rfl

lemma cechFreeEvalHomotopyEquiv_hom_f_zero :
    (cechFreeEvalHomotopyEquiv f W).hom.f 0 = (cechFreeToSieve f).app (op W) :=
  (AlternatingFaceMapComplex.ε_app_f_zero _).trans (Category.comp_id _)

lemma cechFreeEvalHomotopyEquiv_hom_f_succ (n : ℕ) :
    (cechFreeEvalHomotopyEquiv f W).hom.f (n + 1) = 0 :=
  AlternatingFaceMapComplex.ε_app_f_succ _ n

lemma cechFreePresheafComplex_d_comp_toSieve_app :
    ((cechFreePresheafComplex f).d 1 0).app (op W) ≫ (cechFreeToSieve f).app (op W) = 0 := by
  rw [cechFreePresheafComplex_d_app, ← cechFreeEvalHomotopyEquiv_hom_f_zero]
  have h := (cechFreeEvalHomotopyEquiv f W).hom.comm 1 0
  rw [cechFreeEvalHomotopyEquiv_hom_f_succ, zero_comp] at h
  exact h.symm

end Evaluation

lemma cechFreePresheafComplex_d_comp_toSieve :
    (cechFreePresheafComplex f).d 1 0 ≫ cechFreeToSieve f = 0 := by
  ext X : 2
  obtain ⟨W⟩ := X
  rw [NatTrans.comp_app]
  exact (cechFreePresheafComplex_d_comp_toSieve_app f W).trans (NatTrans.app_zero _).symm

section Exactness

variable (W)

lemma cechFreeEval_exact_zero :
    ((ShortComplex.mk ((cechFreePresheafComplex f).d 1 0) (cechFreeToSieve f)
      (cechFreePresheafComplex_d_comp_toSieve f)).map
        ((evaluation Cᵒᵖ AddCommGrpCat.{u + 1}).obj (op W))).Exact := by
  rw [ShortComplex.ab_exact_iff]
  intro x₂ hx₂
  set e := cechFreeEvalHomotopyEquiv f W with he
  have hcomm := e.homotopyHomInvId.comm 0
  rw [Homotopy.dNext_zero_chainComplex, Homotopy.prevD_chainComplex, zero_add] at hcomm
  have h0 : e.hom.f 0 x₂ = 0 := by
    rw [cechFreeEvalHomotopyEquiv_hom_f_zero]
    exact hx₂
  have happ := ConcreteCategory.congr_hom hcomm x₂
  simp only [HomologicalComplex.comp_f, HomologicalComplex.id_f,
    ConcreteCategory.comp_apply, ConcreteCategory.id_apply, AddCommGrpCat.hom_add,
    AddMonoidHom.add_apply, h0, map_zero] at happ
  refine ⟨-(e.homotopyHomInvId.hom 0 1 x₂), ?_⟩
  have : ((cechFreePresheafComplex f).d 1 0).app (op W) =
      (cechFreeEvalComplex f W).d 1 0 := cechFreePresheafComplex_d_app f W 0
  rw [show ((ShortComplex.mk ((cechFreePresheafComplex f).d 1 0) (cechFreeToSieve f)
      (cechFreePresheafComplex_d_comp_toSieve f)).map
        ((evaluation Cᵒᵖ AddCommGrpCat.{u + 1}).obj (op W))).f =
      ((cechFreePresheafComplex f).d 1 0).app (op W) from rfl, this, map_neg]
  exact add_eq_zero_iff_neg_eq.mp happ.symm

lemma cechFreeEval_exact_succ (n : ℕ) :
    ((ShortComplex.mk ((cechFreePresheafComplex f).d (n + 2) (n + 1))
      ((cechFreePresheafComplex f).d (n + 1) n) ((cechFreePresheafComplex f).d_comp_d _ _ _)).map
        ((evaluation Cᵒᵖ AddCommGrpCat.{u + 1}).obj (op W))).Exact := by
  rw [ShortComplex.ab_exact_iff]
  intro x₂ hx₂
  set e := cechFreeEvalHomotopyEquiv f W with he
  have hcomm := e.homotopyHomInvId.comm (n + 1)
  rw [Homotopy.dNext_succ_chainComplex, Homotopy.prevD_chainComplex] at hcomm
  have h0 : e.hom.f (n + 1) x₂ = 0 := by
    rw [cechFreeEvalHomotopyEquiv_hom_f_succ]
    rfl
  have hd : (cechFreeEvalComplex f W).d (n + 1) n x₂ = 0 := by
    rw [← cechFreePresheafComplex_d_app]
    exact hx₂
  have happ := ConcreteCategory.congr_hom hcomm x₂
  simp only [HomologicalComplex.comp_f, HomologicalComplex.id_f,
    ConcreteCategory.comp_apply, ConcreteCategory.id_apply, AddCommGrpCat.hom_add,
    AddMonoidHom.add_apply, h0, hd, map_zero, zero_add] at happ
  refine ⟨-(e.homotopyHomInvId.hom (n + 1) (n + 2) x₂), ?_⟩
  rw [show ((ShortComplex.mk ((cechFreePresheafComplex f).d (n + 2) (n + 1))
      ((cechFreePresheafComplex f).d (n + 1) n)
      ((cechFreePresheafComplex f).d_comp_d _ _ _)).map
        ((evaluation Cᵒᵖ AddCommGrpCat.{u + 1}).obj (op W))).f =
      ((cechFreePresheafComplex f).d (n + 2) (n + 1)).app (op W) from rfl,
    cechFreePresheafComplex_d_app f W (n + 1), map_neg]
  exact add_eq_zero_iff_neg_eq.mp happ.symm

lemma surjective_cechNerveToSieve_app :
    Function.Surjective ((cechNerveToSieve f (op ⦋0⦌)).app (op W)) := by
  rintro ⟨⟨g, hg⟩⟩
  exact ⟨ULift.up (WidePullback.lift g (fun _ => cechSplitting f hg)
      (fun _ => cechSplitting_comp f hg)),
    congrArg ULift.up (Subtype.ext (WidePullback.lift_base _ _ _ _))⟩

end Exactness

lemma epi_cechFreeToSieve : Epi (cechFreeToSieve f) := by
  haveI h : ∀ X : Cᵒᵖ, Epi ((cechFreeToSieve f).app X) := by
    intro X
    change Epi (AddCommGrpCat.free.map ((cechNerveToSieve f (op ⦋0⦌)).app X))
    have : Epi ((cechNerveToSieve f (op ⦋0⦌)).app X) :=
      (epi_iff_surjective _).2 (surjective_cechNerveToSieve_app f X.unop)
    infer_instance
  exact NatTrans.epi_of_epi_app _

omit [HasFiniteWidePullbacks C] in
/-- A short complex of presheaves of abelian groups is exact if all its evaluations are. -/
lemma shortComplex_exact_of_evaluation (S : ShortComplex (Cᵒᵖ ⥤ AddCommGrpCat.{u + 1}))
    (hS : ∀ X : Cᵒᵖ, (S.map ((evaluation Cᵒᵖ AddCommGrpCat.{u + 1}).obj X)).Exact) :
    S.Exact := by
  rw [ShortComplex.exact_iff_isZero_homology]
  apply Functor.isZero
  intro X
  have h := hS X
  rw [ShortComplex.exact_iff_isZero_homology] at h
  exact h.of_iso (S.mapHomologyIso ((evaluation Cᵒᵖ AddCommGrpCat.{u + 1}).obj X)).symm

omit [HasFiniteWidePullbacks C] [HasWeakSheafify J AddCommGrpCat.{u + 1}] in
/-- If `φ` is a morphism of presheaves of types that becomes an isomorphism after
sheafification, then so does the induced morphism of free abelian presheaves. -/
lemma GrothendieckTopology.W.whiskerRight_free {P Q : Cᵒᵖ ⥤ Type (u + 1)} {φ : P ⟶ Q}
    (hφ : J.W φ) : J.W (Functor.whiskerRight φ AddCommGrpCat.free.{u + 1}) := by
  intro T hT
  have hT' : Presheaf.IsSheaf J (T ⋙ forget AddCommGrpCat.{u + 1}) :=
    ((sheafCompose J (forget AddCommGrpCat.{u + 1})).obj ⟨T, hT⟩).property
  have heq : (fun g : _ ⟶ T => Functor.whiskerRight φ AddCommGrpCat.free.{u + 1} ≫ g) =
      ((Adjunction.whiskerRight Cᵒᵖ AddCommGrpCat.adj.{u + 1}).homEquiv P T).symm ∘
        (fun g => φ ≫ g) ∘
          ((Adjunction.whiskerRight Cᵒᵖ AddCommGrpCat.adj.{u + 1}).homEquiv Q T) := by
    funext g
    rw [Function.comp_apply, Function.comp_apply, ← Adjunction.homEquiv_naturality_left,
      Equiv.symm_apply_apply]
    rfl
  rw [heq]
  exact (Equiv.bijective _).comp ((hφ _ hT').comp (Equiv.bijective _))

omit [HasFiniteWidePullbacks C] in
/-- If `f` generates a covering sieve, the inclusion of the sieve into `yoneda U` becomes
an isomorphism of free abelian sheaves after sheafification. -/
lemma isIso_presheafToSheaf_map_whiskerRight_inclusion
    (hf : Sieve.generate (Presieve.singleton f) ∈ J U) :
    IsIso ((presheafToSheaf J AddCommGrpCat.{u + 1}).map
      (Functor.whiskerRight
        (Sieve.uliftFunctorInclusion.{u + 1} (Sieve.generate (Presieve.singleton f)))
        AddCommGrpCat.free)) := by
  rw [← GrothendieckTopology.W_iff]
  apply GrothendieckTopology.W.whiskerRight_free
  haveI : Presheaf.IsLocallyInjective J
      (Sieve.uliftFunctorInclusion.{u + 1} (Sieve.generate (Presieve.singleton f))) := by
    apply Presheaf.isLocallyInjective_of_injective
    intro X a b hab
    exact ULift.ext _ _ (Subtype.ext (congrArg ULift.down hab))
  haveI : Presheaf.IsLocallySurjective J
      (Sieve.uliftFunctorInclusion.{u + 1} (Sieve.generate (Presieve.singleton f))) := by
    constructor
    intro X s
    refine J.superset_covering ?_ (J.pullback_stable s.down hf)
    intro Y h hh
    exact ⟨⟨⟨h ≫ s.down, hh⟩⟩, rfl⟩
  exact J.W_of_isLocallyBijective _

/-- The factorization of the Čech augmentation through the free abelian sheaf on
the sieve generated by `f`. -/
lemma cechFreeAug_eq :
    cechFreeAug J f = (presheafToSheaf J AddCommGrpCat.{u + 1}).map (cechFreeToSieve f) ≫
      (presheafToSheaf J AddCommGrpCat.{u + 1}).map
        (Functor.whiskerRight
          (Sieve.uliftFunctorInclusion.{u + 1} (Sieve.generate (Presieve.singleton f)))
          AddCommGrpCat.free) := by
  have h : cechFreeAug J f = (presheafToSheaf J AddCommGrpCat.{u + 1}).map
      (freeAbelianPresheafFunctor.map ((Arrow.mk f).augmentedCechNerve.hom.app (op ⦋0⦌))) := rfl
  rw [h, freeAbelianPresheafFunctor_map_aug_fac, Functor.map_comp]

end Resolution

theorem cechFreeD_comp_aug : cechFreeD J f 0 ≫ cechFreeAug J f = 0 := by
  have h : cechFreeD J f 0 ≫ cechFreeAug J f =
      (presheafToSheaf J AddCommGrpCat.{u + 1}).map ((cechFreePresheafComplex f).d 1 0 ≫
        freeAbelianPresheafFunctor.map ((Arrow.mk f).augmentedCechNerve.hom.app (op ⦋0⦌))) :=
    ((presheafToSheaf J AddCommGrpCat.{u + 1}).map_comp _ _).symm
  rw [h, freeAbelianPresheafFunctor_map_aug_fac, ← Category.assoc,
    cechFreePresheafComplex_d_comp_toSieve, zero_comp, Functor.map_zero]

/-- If `f` generates a covering sieve, the augmentation of the Čech complex of free
abelian sheaves is an epimorphism. -/
theorem epi_cechFreeAug (hf : Sieve.generate (Presieve.singleton f) ∈ J U) :
    Epi (cechFreeAug J f) := by
  rw [cechFreeAug_eq]
  haveI := isIso_presheafToSheaf_map_whiskerRight_inclusion J f hf
  haveI := epi_cechFreeToSieve f
  exact epi_comp _ _

/-- If `f` generates a covering sieve, the Čech complex of free abelian sheaves
is exact at the augmentation. -/
theorem cechFree_exact_zero (hf : Sieve.generate (Presieve.singleton f) ∈ J U) :
    (ShortComplex.mk (cechFreeD J f 0) (cechFreeAug J f) (cechFreeD_comp_aug J f)).Exact := by
  have hpsh : (ShortComplex.mk ((cechFreePresheafComplex f).d 1 0) (cechFreeToSieve f)
      (cechFreePresheafComplex_d_comp_toSieve f)).Exact := by
    apply shortComplex_exact_of_evaluation
    intro X
    obtain ⟨W⟩ := X
    exact cechFreeEval_exact_zero f W
  have hmap := hpsh.map (presheafToSheaf J AddCommGrpCat.{u + 1})
  haveI := isIso_presheafToSheaf_map_whiskerRight_inclusion J f hf
  refine ShortComplex.exact_of_iso ?_ hmap
  refine ShortComplex.isoMk (Iso.refl _) (Iso.refl _)
    (asIso ((presheafToSheaf J AddCommGrpCat.{u + 1}).map
      (Functor.whiskerRight
        (Sieve.uliftFunctorInclusion.{u + 1} (Sieve.generate (Presieve.singleton f)))
        AddCommGrpCat.free))) ?_ ?_
  · simp only [Iso.refl_hom, Category.id_comp, Category.comp_id]
    rfl
  · simp only [Iso.refl_hom, Category.id_comp, asIso_hom]
    exact cechFreeAug_eq J f

set_option linter.unusedVariables false in
/-- If `f` generates a covering sieve, the Čech complex of free abelian sheaves
is exact in positive degrees. -/
theorem cechFree_exact_succ (hf : Sieve.generate (Presieve.singleton f) ∈ J U) (n : ℕ) :
    (ShortComplex.mk (cechFreeD J f (n + 1)) (cechFreeD J f n)
      (cechFreeD_comp_d J f n)).Exact := by
  have hpsh : (ShortComplex.mk ((cechFreePresheafComplex f).d (n + 2) (n + 1))
      ((cechFreePresheafComplex f).d (n + 1) n)
      ((cechFreePresheafComplex f).d_comp_d _ _ _)).Exact := by
    apply shortComplex_exact_of_evaluation
    intro X
    obtain ⟨W⟩ := X
    exact cechFreeEval_exact_succ f W n
  exact hpsh.map (presheafToSheaf J AddCommGrpCat.{u + 1})

end CategoryTheory
