import Proetale.Algebra.WeaklyEtale
import Proetale.Algebra.IndEtale
import Proetale.Algebra.HenselianLocalRing

universe u

open TensorProduct CategoryTheory Limits

/-- An ideal all of whose elements admit an idempotent multiplier from the ideal is pure. -/
lemma Ideal.Pure.of_forall_exists_isIdempotentElem_mul_eq {A : Type*} [CommRing A]
    {I : Ideal A} (h : ∀ x ∈ I, ∃ e ∈ I, IsIdempotentElem e ∧ x * e = x) : I.Pure := by
  refine Ideal.Pure.of_inf_eq_mul _ fun J _ =>
    le_antisymm (fun x hx => ?_) (Ideal.mul_le_inf)
  obtain ⟨e, heI, -, hxe⟩ := h x hx.1
  rw [← hxe, mul_comm x e]
  exact Ideal.mul_mem_mul heI hx.2

namespace Algebra.IndEtale

variable {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]

/-- Naturality of the multiplication map in algebra homomorphisms. -/
private lemma lmul'_map {C D : Type u} [CommRing C] [CommRing D] [Algebra R C]
    [Algebra R D] (α : C →ₐ[R] D) (y : C ⊗[R] C) :
    Algebra.TensorProduct.lmul' R (Algebra.TensorProduct.map α α y) =
      α (Algebra.TensorProduct.lmul' R y) := by
  induction y with
  | zero => simp
  | tmul a b => simp [Algebra.TensorProduct.lmul'_apply_tmul]
  | add a b ha hb => simp [ha, hb]

variable [Algebra.IndEtale R S]

/-- Every element of the kernel of the multiplication map of an ind-étale algebra admits an
idempotent multiplier from the kernel. Indeed, the element is defined at some étale stage of a
filtered colimit presentation, where the kernel of the multiplication map is generated by a
single idempotent. -/
theorem exists_isIdempotentElem_mul_eq_of_mem_kaehlerDifferential_ideal
    {x : S ⊗[R] S} (hx : x ∈ KaehlerDifferential.ideal R S) :
    ∃ e ∈ KaehlerDifferential.ideal R S, IsIdempotentElem e ∧ x * e = x := by
  classical
  obtain ⟨ι, _, _, P, hP⟩ := Algebra.IndEtale.exists_colimitPresentation (R := R) (S := S)
  let φ : ∀ i : ι, P.diag.obj i →ₐ[R] S := fun i => (P.ι.app i).hom
  let Φ : ∀ i : ι, (P.diag.obj i ⊗[R] P.diag.obj i) →ₐ[R] S ⊗[R] S := fun i =>
    Algebra.TensorProduct.map (φ i) (φ i)
  have hc' := isColimitOfPreserves (CategoryTheory.forget (CommAlgCat R)) P.isColimit
  have hφcomp : ∀ {i j : ι} (f : i ⟶ j), (φ j).comp (P.diag.map f).hom = φ i := fun f => by
    simp only [φ]
    rw [← CommAlgCat.hom_comp, P.w]
  -- Every element of `S ⊗[R] S` is defined at some stage.
  have hsurj : ∀ z : S ⊗[R] S, ∃ (i : ι) (y : P.diag.obj i ⊗[R] P.diag.obj i), Φ i y = z := by
    intro z
    induction z with
    | zero => exact ⟨IsFiltered.nonempty.some, 0, map_zero _⟩
    | tmul a b =>
      obtain ⟨i, a', ha⟩ := Types.jointly_surjective_of_isColimit hc' a
      obtain ⟨j, b', hb⟩ := Types.jointly_surjective_of_isColimit hc' b
      replace ha : φ i a' = a := by simpa using ha
      replace hb : φ j b' = b := by simpa using hb
      refine ⟨IsFiltered.max i j, (P.diag.map (IsFiltered.leftToMax i j)).hom a' ⊗ₜ
        (P.diag.map (IsFiltered.rightToMax i j)).hom b', ?_⟩
      have ha' : φ _ ((P.diag.map (IsFiltered.leftToMax i j)).hom a') = a := by
        rw [← AlgHom.comp_apply, hφcomp]
        exact ha
      have hb' : φ _ ((P.diag.map (IsFiltered.rightToMax i j)).hom b') = b := by
        rw [← AlgHom.comp_apply, hφcomp]
        exact hb
      simp [Φ, ha', hb']
    | add z₁ z₂ h₁ h₂ =>
      obtain ⟨i₁, y₁, hy₁⟩ := h₁
      obtain ⟨i₂, y₂, hy₂⟩ := h₂
      refine ⟨IsFiltered.max i₁ i₂,
        Algebra.TensorProduct.map (P.diag.map (IsFiltered.leftToMax i₁ i₂)).hom
          (P.diag.map (IsFiltered.leftToMax i₁ i₂)).hom y₁ +
        Algebra.TensorProduct.map (P.diag.map (IsFiltered.rightToMax i₁ i₂)).hom
          (P.diag.map (IsFiltered.rightToMax i₁ i₂)).hom y₂, ?_⟩
      rw [map_add, ← AlgHom.comp_apply, ← AlgHom.comp_apply, ← Algebra.TensorProduct.map_comp,
        ← Algebra.TensorProduct.map_comp, hφcomp, hφcomp, hy₁, hy₂]
  obtain ⟨i, w, hw⟩ := hsurj x
  -- The multiplication of `w` dies at some later stage.
  have h0 : φ i (Algebra.TensorProduct.lmul' R w) = 0 := by
    rw [← lmul'_map (φ i) w, hw]
    exact hx
  have heq : φ i (Algebra.TensorProduct.lmul' R w) = φ i 0 := by
    rw [h0, map_zero]
  obtain ⟨k, f, g, hfg⟩ := (Types.FilteredColimit.isColimit_eq_iff
    (P.diag ⋙ CategoryTheory.forget (CommAlgCat R)) hc').mp heq
  have hfg' : (P.diag.map f).hom (Algebra.TensorProduct.lmul' R w) = 0 := by
    have h2 : (P.diag.map g).hom (0 : P.diag.obj i) = 0 := map_zero _
    exact hfg.trans h2
  -- At stage `k`, the element lies in the diagonal ideal, which is generated by an idempotent.
  haveI : Algebra.Etale R (P.diag.obj k) := hP k
  set w' : P.diag.obj k ⊗[R] P.diag.obj k :=
    Algebra.TensorProduct.map (P.diag.map f).hom (P.diag.map f).hom w with hw'def
  have hw' : w' ∈ KaehlerDifferential.ideal R (P.diag.obj k) := by
    rw [RingHom.mem_ker, ← AlgHom.coe_toRingHom, AlgHom.coe_toRingHom, lmul'_map, hfg']
  obtain ⟨e₀, he₀, hsp⟩ : ∃ e₀, IsIdempotentElem e₀ ∧
      KaehlerDifferential.ideal R (P.diag.obj k) = (P.diag.obj k ⊗[R] P.diag.obj k) ∙ e₀ :=
    (Ideal.isIdempotentElem_iff_of_fg _ (KaehlerDifferential.ideal_fg R _)).mp <|
      (Ideal.cotangent_subsingleton_iff _).mp <|
        inferInstanceAs <| Subsingleton (Ω[P.diag.obj k⁄R])
  have he₀mem : e₀ ∈ KaehlerDifferential.ideal R (P.diag.obj k) := by
    rw [hsp]
    exact Submodule.mem_span_singleton_self e₀
  -- `w' * e₀ = w'` since `w'` is a multiple of the idempotent `e₀`.
  have hmul : w' * e₀ = w' := by
    have : w' ∈ (P.diag.obj k ⊗[R] P.diag.obj k) ∙ e₀ := hsp ▸ hw'
    obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp this
    rw [← hc, smul_eq_mul, mul_assoc, he₀]
  -- Push everything forward to `S ⊗[R] S`.
  have hΦw' : Φ k w' = x := by
    rw [hw'def, ← AlgHom.comp_apply, ← Algebra.TensorProduct.map_comp, hφcomp, hw]
  refine ⟨Φ k e₀, ?_, he₀.map (Φ k), ?_⟩
  · rw [RingHom.mem_ker, ← AlgHom.coe_toRingHom, AlgHom.coe_toRingHom, lmul'_map]
    rw [RingHom.mem_ker] at he₀mem
    rw [he₀mem, map_zero]
  · rw [← hΦw', ← map_mul, hmul]

/-- An ind-étale algebra is weakly étale. Stacks 097K. -/
@[stacks 097K]
instance (priority := 100) weaklyEtale : Algebra.WeaklyEtale R S where
  flat := by
    rw [Module.Flat.iff_ind_flat]
    obtain ⟨ι, _, _, P, hP⟩ := Algebra.IndEtale.exists_colimitPresentation (R := R) (S := S)
    refine ⟨ι, inferInstance, inferInstance, P, fun i => ?_⟩
    rw [CommAlgCat.flat_iff]
    haveI : Algebra.Etale R (P.diag.obj i) := hP i
    infer_instance
  flat_lmul' :=
    Algebra.flat_lmul'_iff_kaehlerDifferential_ideal_pure.mpr <|
      Ideal.Pure.of_forall_exists_isIdempotentElem_mul_eq fun _ hx =>
        exists_isIdempotentElem_mul_eq_of_mem_kaehlerDifferential_ideal hx

end Algebra.IndEtale

section LocalizationBase

variable {A A' B : Type u} [CommRing A] [CommRing A'] [CommRing B]

/-- Weak étaleness descends along a localization of the base: if `B` is weakly étale over `A`
and `B` is an algebra over a localization `A'` of `A`, then `B` is weakly étale over `A'`. -/
theorem Algebra.WeaklyEtale.localization_base (M : Submonoid A) [Algebra A A']
    [IsLocalization M A'] [Algebra A B] [Algebra A' B] [IsScalarTower A A' B]
    [Algebra.WeaklyEtale A B] : Algebra.WeaklyEtale A' B where
  flat := (Module.flat_iff_of_isLocalization (S := A') (p := M) (M := B)).mpr inferInstance
  flat_lmul' := by
    have hcompat : TensorProduct.CompatibleSMul A A' B B :=
      IsLocalization.tensorProduct_compatibleSMul M A' B B
    let e : B ⊗[A'] B ≃ₐ[A'] B ⊗[A] B :=
      Algebra.TensorProduct.equivOfCompatibleSMul A A' A' B B
    have key : (Algebra.TensorProduct.lmul' A' (S := B)).toRingHom =
        (Algebra.TensorProduct.lmul' A (S := B)).toRingHom.comp (e : B ⊗[A'] B →+* B ⊗[A] B) := by
      refine RingHom.ext fun x => ?_
      induction x with
      | zero => simp
      | tmul a b =>
        simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_comp, RingHom.coe_coe,
          Function.comp_apply, Algebra.TensorProduct.lmul'_apply_tmul]
        rw [show (e (a ⊗ₜ[A'] b) : B ⊗[A] B) = a ⊗ₜ[A] b from rfl,
          Algebra.TensorProduct.lmul'_apply_tmul]
      | add x y hx hy => simp_all [map_add]
    change (Algebra.TensorProduct.lmul' A' (S := B)).toRingHom.Flat
    rw [key]
    exact RingHom.Flat.comp (.of_bijective e.bijective) (Algebra.WeaklyEtale.flat_lmul' A B)

end LocalizationBase

section LocalizationLocalization

variable {B : Type u} [CommRing B]

/-- Localizing a localization of `B` at a prime lying over the prime `q` of `B` gives the
localization of `B` at `q`: the canonical map is bijective. -/
theorem Localization.bijective_localRingHom_algebraMap_of_comap_eq (M : Submonoid B)
    (q₁ : Ideal (Localization M)) [q₁.IsPrime] (q : Ideal B) [q.IsPrime]
    (hq : q = q₁.comap (algebraMap B (Localization M))) :
    Function.Bijective
      (Localization.localRingHom q q₁ (algebraMap B (Localization M)) hq) := by
  subst hq
  -- `Localization.AtPrime q₁` is an `AtPrime` localization of `B` itself.
  haveI : IsLocalization.AtPrime (Localization.AtPrime q₁)
      (q₁.comap (algebraMap B (Localization M))) :=
    IsLocalization.isLocalization_atPrime_localization_atPrime M q₁
  set q := q₁.comap (algebraMap B (Localization M))
  -- The canonical comparison `AlgEquiv` between the two `AtPrime q` localizations.
  let e := IsLocalization.algEquiv q.primeCompl (Localization.AtPrime q)
    (Localization.AtPrime q₁)
  have he : Localization.localRingHom q q₁ (algebraMap B (Localization M)) rfl =
      (e : Localization.AtPrime q →+* Localization.AtPrime q₁) := by
    apply IsLocalization.ringHom_ext q.primeCompl
    refine RingHom.ext fun b => ?_
    rw [RingHom.comp_apply, RingHom.comp_apply, Localization.localRingHom_to_map,
      RingHom.coe_coe, IsLocalization.algEquiv_apply, IsLocalization.map_eq,
      ← IsScalarTower.algebraMap_apply]
    rfl
  rw [he]
  exact e.bijective

end LocalizationLocalization

section StrictlyHenselian

open IsLocalRing

variable {A B : Type u} [CommRing A] [CommRing B] [Algebra A B]

/-- Blueprint `thm:ind-etale-strictly-henselian-localization-isom`, weakly étale version
(which covers the ind-étale case): if `A` is strictly henselian and `B` is weakly étale
over `A`, then for every prime `n` of `B` lying over the maximal ideal of `A` the canonical
map `A → B_n` is bijective. -/
theorem Algebra.WeaklyEtale.bijective_algebraMap_localization_atPrime
    [IsStrictlyHenselianLocalRing A] [Algebra.WeaklyEtale A B] (n : Ideal B) [n.IsPrime]
    (hn : n.comap (algebraMap A B) = maximalIdeal A) :
    Function.Bijective (algebraMap A (Localization.AtPrime n)) := by
  haveI : Algebra.WeaklyEtale B (Localization.AtPrime n) :=
    .of_isLocalization B n.primeCompl _
  haveI : Algebra.WeaklyEtale A (Localization.AtPrime n) := .trans A B _
  haveI : IsLocalHom (algebraMap A (Localization.AtPrime n)) := by
    apply ((IsLocalRing.local_hom_TFAE (algebraMap A (Localization.AtPrime n))).out 0 4).mpr
    rw [IsScalarTower.algebraMap_eq A B (Localization.AtPrime n), ← Ideal.comap_comap,
      show (IsLocalRing.maximalIdeal (Localization.AtPrime n)).comap
          (algebraMap B (Localization.AtPrime n)) = n from
        Localization.AtPrime.under_maximalIdeal, hn]
  exact Algebra.WeaklyEtale.bijective_of_isStrictlyHenselianLocalRing

/-- The stalkwise version of
`Algebra.WeaklyEtale.bijective_algebraMap_localization_atPrime`: for a weakly étale
algebra `B` over `A` and a prime `n` of `B` such that the localization of `A` at `n ∩ A` is
strictly henselian, the stalk map `A_{n ∩ A} → B_n` is bijective. -/
theorem Algebra.WeaklyEtale.bijective_localRingHom_of_isStrictlyHenselianLocalRing
    [Algebra.WeaklyEtale A B] (n : Ideal B) [n.IsPrime]
    [IsStrictlyHenselianLocalRing (Localization.AtPrime (n.comap (algebraMap A B)))] :
    Function.Bijective
      (Localization.localRingHom (n.comap (algebraMap A B)) n (algebraMap A B) rfl) := by
  haveI : (n.comap (algebraMap A B)).IsPrime := ‹n.IsPrime›.comap (algebraMap A B)
  set m := n.comap (algebraMap A B) with hm
  set A' := Localization.AtPrime m with hA'
  set L := Localization.AtPrime n with hLdef
  letI : Algebra A' L := (Localization.localRingHom m n (algebraMap A B) rfl).toAlgebra
  haveI : IsScalarTower A A' L := .of_algebraMap_eq fun a => by
    change algebraMap A L a = Localization.localRingHom m n (algebraMap A B) rfl
      (algebraMap A A' a)
    rw [Localization.localRingHom_to_map, ← IsScalarTower.algebraMap_apply]
  haveI : Algebra.WeaklyEtale B L := .of_isLocalization B n.primeCompl _
  haveI : Algebra.WeaklyEtale A L := .trans A B _
  haveI : Algebra.WeaklyEtale A' L := .localization_base m.primeCompl
  haveI : IsLocalHom (algebraMap A' L) :=
    Localization.isLocalHom_localRingHom m n (algebraMap A B) rfl
  exact Algebra.WeaklyEtale.bijective_of_isStrictlyHenselianLocalRing

/-- A weakly étale algebra `B` over `A` is bijective on stalks as soon as every prime of `B` is
contained in a prime `n` for which the localization of `A` at `n ∩ A` is strictly henselian.

This is the key step of the blueprint lemma
`thm:ind-etale-plus-c-has-retraction-if-w-contractible`: the stalk maps at such primes `n` are
bijective, and stalk maps at smaller primes are further localizations of these. -/
theorem Algebra.WeaklyEtale.bijectiveOnStalks [Algebra.WeaklyEtale A B]
    (hmax : ∀ (q : Ideal B) [q.IsPrime], ∃ (n : Ideal B) (hn : n.IsPrime), q ≤ n ∧
      (letI := hn
       letI : (n.comap (algebraMap A B)).IsPrime := hn.comap (algebraMap A B)
       IsStrictlyHenselianLocalRing (Localization.AtPrime (n.comap (algebraMap A B))))) :
    Algebra.BijectiveOnStalks A B := by
  constructor
  intro q hq
  obtain ⟨n, hn, hqn, hsh⟩ := hmax q
  haveI := hn
  haveI : (n.comap (algebraMap A B)).IsPrime := hn.comap (algebraMap A B)
  haveI : IsStrictlyHenselianLocalRing (Localization.AtPrime (n.comap (algebraMap A B))) := hsh
  set f := algebraMap A B
  set p := q.comap f
  set m := n.comap f
  set A' := Localization.AtPrime m with hA'
  set L := Localization.AtPrime n with hL
  set ψ := Localization.localRingHom m n f rfl with hψ
  have hψbij : Function.Bijective ψ :=
    Algebra.WeaklyEtale.bijective_localRingHom_of_isStrictlyHenselianLocalRing n
  -- The prime of `L` lying over `q`.
  have hdisj : Disjoint (n.primeCompl : Set B) (q : Set B) := by
    rw [Set.disjoint_iff]
    rintro x ⟨hx1, hx2⟩
    exact hx1 (hqn hx2)
  set q₁ : Ideal L := q.map (algebraMap B L) with hq₁def
  haveI hq₁prime : q₁.IsPrime :=
    IsLocalization.isPrime_of_isPrime_disjoint n.primeCompl L q hq hdisj
  have hq₁comap : q₁.comap (algebraMap B L) = q :=
    IsLocalization.under_map_of_isPrime_disjoint n.primeCompl L hq hdisj
  -- The prime of `A'` lying over `p`.
  set p₁ : Ideal A' := q₁.comap ψ with hp₁def
  haveI hp₁prime : p₁.IsPrime := hq₁prime.comap ψ
  -- The two composites `A → L` agree.
  have hcomm : ψ.comp (algebraMap A A') = (algebraMap B L).comp f := by
    refine RingHom.ext fun a => ?_
    rw [RingHom.comp_apply, RingHom.comp_apply]
    exact Localization.localRingHom_to_map m n f rfl a
  have hp₁comap : p₁.comap (algebraMap A A') = p := by
    rw [hp₁def, Ideal.comap_comap, hcomm, ← Ideal.comap_comap, hq₁comap]
  -- Decompose the localization of the composite in two ways.
  have hcomp₁ : Localization.localRingHom p q₁ ((algebraMap B L).comp f)
        (by rw [← Ideal.comap_comap, hq₁comap]) =
      (Localization.localRingHom q q₁ (algebraMap B L) hq₁comap.symm).comp
        (Localization.localRingHom p q f rfl) :=
    Localization.localRingHom_comp p q q₁ f rfl (algebraMap B L) hq₁comap.symm
  have hcomp₂ : Localization.localRingHom p q₁ (ψ.comp (algebraMap A A'))
        (by rw [← Ideal.comap_comap, ← hp₁def, hp₁comap]) =
      (Localization.localRingHom p₁ q₁ ψ rfl).comp
        (Localization.localRingHom p p₁ (algebraMap A A') hp₁comap.symm) :=
    Localization.localRingHom_comp p p₁ q₁ (algebraMap A A') hp₁comap.symm ψ rfl
  -- The left-hand sides agree.
  have hlhs : Localization.localRingHom p q₁ ((algebraMap B L).comp f)
        (by rw [← Ideal.comap_comap, hq₁comap]) =
      Localization.localRingHom p q₁ (ψ.comp (algebraMap A A'))
        (by rw [← Ideal.comap_comap, ← hp₁def, hp₁comap]) := by
    apply Localization.localRingHom_unique
    intro x
    rw [Localization.localRingHom_to_map, hcomm]
  -- All the outer maps are bijective.
  have hb : Function.Bijective (Localization.localRingHom q q₁ (algebraMap B L) hq₁comap.symm) :=
    Localization.bijective_localRingHom_algebraMap_of_comap_eq n.primeCompl q₁ q hq₁comap.symm
  have hc : Function.Bijective
      (Localization.localRingHom p p₁ (algebraMap A A') hp₁comap.symm) :=
    Localization.bijective_localRingHom_algebraMap_of_comap_eq m.primeCompl p₁ p hp₁comap.symm
  have hd : Function.Bijective (Localization.localRingHom p₁ q₁ ψ rfl) := by
    have := (RingEquiv.ofBijective ψ hψbij).bijectiveOnStalks q₁
    exact this
  -- Two-out-of-three.
  have hcomposite : Function.Bijective
      ((Localization.localRingHom q q₁ (algebraMap B L) hq₁comap.symm).comp
        (Localization.localRingHom p q f rfl)) := by
    rw [← hcomp₁, hlhs, hcomp₂]
    exact hd.comp hc
  constructor
  · intro x y hxy
    refine hcomposite.injective ?_
    simp only [RingHom.comp_apply]
    exact congrArg _ hxy
  · intro y
    obtain ⟨x, hx⟩ := hcomposite.surjective
      (Localization.localRingHom q q₁ (algebraMap B L) hq₁comap.symm y)
    exact ⟨x, hb.injective hx⟩

end StrictlyHenselian

lemma RingHom.IndEtale.weaklyEtale {R S : Type u} [CommRing R] [CommRing S] {f : R →+* S}
    (hf : f.IndEtale) :
    f.WeaklyEtale := by
  algebraize [f]
  rw [← RingHom.algebraMap_toAlgebra f, weaklyEtale_algebraMap_iff]
  infer_instance

/-- If `S` is a weakly étale `R`-algebra, there exists a faithfully flat, ind-étale `S`-algebra `T`
such that `T` is an ind-étale `R`-algebra. -/
theorem Algebra.WeaklyEtale.exists_indEtale (R S : Type u) [CommRing R] [CommRing S]
    [Algebra R S] [WeaklyEtale R S] :
    ∃ (T : Type u) (_ : CommRing T) (_ : Algebra R T) (_ : Algebra S T) (_ : IsScalarTower R S T),
      IndEtale S T ∧ Module.FaithfullyFlat S T ∧ IndEtale R T :=
  sorry

/-- If `S` is a weakly étale `R`-algebra, there exists a faithfully flat, ind-étale `S`-algebra `T`
such that `T` is an ind-étale `R`-algebra. -/
theorem RingHom.WeaklyEtale.exists_indEtale_comp {R S : Type u} [CommRing R] [CommRing S]
    {f : R →+* S} (hf : f.WeaklyEtale) :
    ∃ (T : Type u) (_ : CommRing T) (g : S →+* T),
      g.IndEtale ∧ g.FaithfullyFlat ∧ (g.comp f).IndEtale := by
  algebraize [f]
  obtain ⟨T, _, _, _, _, h₁, h₂, h₃⟩ := Algebra.WeaklyEtale.exists_indEtale R S
  refine ⟨T, inferInstance, algebraMap S T, ?_, ?_, ?_⟩
  · rwa [IndEtale.algebraMap_iff]
  · rwa [faithfullyFlat_algebraMap_iff]
  · rwa [← RingHom.algebraMap_toAlgebra f, ← IsScalarTower.algebraMap_eq, IndEtale.algebraMap_iff]
