/-
Copyright (c) 2026 Christian Merten, Jingting Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten, Jingting Wang
-/
import Proetale.Algebra.WeaklyEtale
import Mathlib

/-!
# Weak dimension of a commutative ring

Since mathlib does not have `Tor`, we only define some special cases in low dimensions.
-/

/-- A ring `R` is absolutely flat if every ideal of `R` is pure, i.e. `R ⧸ I` is flat. -/
class Ring.AbsolutelyFlat (R : Type*) [CommRing R] where
  flat (I : Ideal R) : Module.Flat R (R ⧸ I)

/-- A ring `R` is of weak dimension `≤ 1` if any finitely generated ideal is flat. -/
class Ring.WeakDimensionLEOne (R : Type*) [CommRing R] where
  flat_of_fg (I : Ideal R) : I.FG → Module.Flat R I

/-- If `f : R →+* S` is a surjective flat ring map and `f x = 0`, then there exists `y : R`
such that `f y = 1` and `y * x = 0`. This expresses that the kernel of a surjective flat
map is pure. -/
lemma exists_eq_mul_of_surjective_flat {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (hf : f.Flat) (hsurj : Function.Surjective f)
    (x : R) (hx : f x = 0) : ∃ y : R, f y = 1 ∧ y * x = 0 := by
  algebraize [f]
  have e : (R ⧸ RingHom.ker f) ≃ₐ[R] S :=
    AlgEquiv.ofRingEquiv (f := f.quotientKerEquivOfSurjective hsurj) fun _ ↦ rfl
  have : (RingHom.ker f).Pure := Module.Flat.of_linearEquiv e.toLinearEquiv
  obtain ⟨z, hzker, hxz⟩ := Ideal.exists_eq_mul_of_pure (show x ∈ RingHom.ker f from hx)
  refine ⟨1 - z, ?_, ?_⟩
  · rw [map_sub, map_one, RingHom.mem_ker.mp hzker, sub_zero]
  · rw [sub_mul, one_mul, mul_comm, ← hxz, sub_self]

lemma exists_eq_mul_of_surjective_flat' {R S ι : Type*} [CommRing R] [CommRing S] [Finite ι]
    (f : R →+* S) (hf : f.Flat) (hsurj : Function.Surjective f)
    (x : ι → R) (hx : ∀ i, f (x i) = 0) : ∃ y : R, f y = 1 ∧ ∀ i : ι, y * x i = 0 := by
  induction ι using Finite.induction_empty_option with
  | of_equiv e h =>
    obtain ⟨y, hy, hy'⟩ := h (x.comp e) (by grind)
    refine ⟨y, hy, fun i ↦ by simpa using hy' (e.symm i)⟩
  | h_empty => exact ⟨1, by simp, by simp⟩
  | h_option h =>
    obtain ⟨y, hy, hy'⟩ := h (x.comp Option.some) (by grind)
    obtain ⟨z, hz, hz'⟩ := exists_eq_mul_of_surjective_flat f hf hsurj (x .none) (by grind)
    refine ⟨y * z, by simp [hy, hz], fun | some i => by grind | none => by grind⟩

/-- A finitely generated `Π i, A i`-submodule `N` of a product `Π i, M i` is the product of its
componentwise images: if every component `y i` of `y` lies in the image of `N` under the `i`-th
projection, then `y ∈ N`. -/
theorem Submodule.FG.mem_pi {ι : Type*} {A : ι → Type*} [∀ i, Semiring (A i)]
    {M : ι → Type*} [∀ i, AddCommMonoid (M i)] [∀ i, Module (A i) (M i)]
    {N : Submodule (Π i, A i) (Π i, M i)} (hN : N.FG)
    {y : Π i, M i} (hy : ∀ i, ∃ z ∈ N, z i = y i) : y ∈ N := by
  classical
  obtain ⟨s, hs⟩ := hN
  choose z hzN hzy using hy
  rw [← hs] at hzN ⊢
  choose c _hcs hc using fun i ↦ Submodule.mem_span_finset.mp (hzN i)
  have hy_eq : y = ∑ a ∈ s, (fun j ↦ c j a j) • a := by
    ext i
    rw [← hzy i, ← hc i]
    simp [Finset.sum_apply]
  rw [hy_eq]
  exact Submodule.sum_mem _ fun a ha ↦ Submodule.smul_mem _ _ (Submodule.subset_span ha)

namespace Ring.WeakDimensionLEOne

variable (R : Type*) [CommRing R] {S : Type*} [CommRing S] [Algebra R S]

/-- If `R` is of weak dimension `≤ 1`, then any submodule of a flat module is flat. -/
lemma flat_submodule [Ring.WeakDimensionLEOne R] {M : Type*} [AddCommGroup M] [Module R M]
    (N : Submodule R M) [Module.Flat R M] :
    Module.Flat R N := by
  rw [Module.Flat.iff_lTensor_injective]
  intro I hI
  have : Module.Flat R I := Ring.WeakDimensionLEOne.flat_of_fg I hI
  have h : Function.Injective (⇑(I.subtype.lTensor M) ∘ ⇑(N.subtype.rTensor I)) :=
    (Module.Flat.lTensor_preserves_injective_linearMap _ I.injective_subtype).comp
      (Module.Flat.rTensor_preserves_injective_linearMap _ N.injective_subtype)
  have hnat : ⇑(I.subtype.lTensor M) ∘ ⇑(N.subtype.rTensor I) =
      ⇑(N.subtype.rTensor R) ∘ ⇑(I.subtype.lTensor N) := by
    rw [← LinearMap.coe_comp, LinearMap.lTensor_comp_rTensor,
      ← LinearMap.rTensor_comp_lTensor, LinearMap.coe_comp]
  exact (hnat ▸ h).of_comp

lemma flat_ideal [Ring.WeakDimensionLEOne R] (I : Ideal R) :
    Module.Flat R I :=
  flat_submodule _ _

/-- The product of valuation rings is of weak dimension `≤ 1`. -/
lemma pi_of_isValuationRing {ι : Type*} (R : ι → Type*) [∀ i, CommRing (R i)]
    [∀ i, IsDomain (R i)] [∀ i, ValuationRing (R i)] :
    WeakDimensionLEOne (Π i, R i) := by
  classical
  refine .mk fun I hI ↦ ?_
  -- Each image ideal is finitely generated over a Bézout ring, hence principal.
  choose f hf using fun i ↦
    (IsBezout.isPrincipal_of_FG _ (hI.map (Pi.evalRingHom R i))).principal
  -- Hence `I` is generated by the function `f`.
  have hfI : I = Ideal.span {(fun i ↦ f i : Π i, R i)} := by
    refine le_antisymm (fun y hy ↦ ?_) ?_
    · have h1 : ∀ i, y i ∈ Submodule.span (R i) {f i} := fun i ↦
        hf i ▸ Ideal.mem_map_of_mem _ hy
      choose c hc using fun i ↦ Submodule.mem_span_singleton.mp (h1 i)
      exact Ideal.mem_span_singleton'.mpr ⟨fun i ↦ c i, funext fun i ↦ hc i⟩
    · rw [Ideal.span_le, Set.singleton_subset_iff]
      refine Submodule.FG.mem_pi hI fun i ↦ ?_
      have hfi : f i ∈ I.map (Pi.evalRingHom R i) := hf i ▸ Submodule.mem_span_singleton_self (f i)
      exact (Ideal.mem_map_iff_of_surjective _ (Function.surjective_eval i)).mp hfi
  rw [hfI]
  -- Decompose `f = g * e` with `e` idempotent and `g` a non-zerodivisor.
  set e : Π i, R i := fun i ↦ if f i = 0 then 0 else 1 with hedef
  set g : Π i, R i := fun i ↦ if f i = 0 then 1 else f i with hgdef
  have hge : (fun i ↦ f i : Π i, R i) = g * e := by
    ext i
    by_cases h : f i = 0 <;> simp [hedef, hgdef, h]
  have hee : e * e = e := by
    ext i
    by_cases h : f i = 0 <;> simp [hedef, h]
  have hgreg : ∀ x : Π i, R i, x * g = 0 → x = 0 := by
    intro x hx
    ext i
    have h1 := congrFun hx i
    by_cases h : f i = 0
    · simpa [hgdef, h] using h1
    · simp only [hgdef, Pi.mul_apply, Pi.zero_apply, if_neg h] at h1
      exact (mul_eq_zero.mp h1).resolve_right h
  -- The span of the idempotent `e` is a retract of the ring, hence flat.
  have hflat_e : Module.Flat (Π i, R i) (Ideal.span {e}) := by
    refine Module.Flat.of_retract (Ideal.span {e}).subtype
      (LinearMap.toSpanSingleton _ _ ⟨e, Ideal.mem_span_singleton_self e⟩) ?_
    refine LinearMap.ext fun ⟨y, hy⟩ ↦ Subtype.ext ?_
    obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.mp hy
    simp only [LinearMap.comp_apply, Submodule.subtype_apply, LinearMap.toSpanSingleton_apply,
      LinearMap.id_coe, id_eq, SetLike.val_smul, smul_eq_mul, mul_assoc, hee]
  -- Multiplication by the non-zerodivisor `g` identifies the spans of `e` and `f = g * e`.
  rw [hge]
  have hsub : ∀ x ∈ Ideal.span {e},
      LinearMap.toSpanSingleton (Π i, R i) (Π i, R i) g x ∈ Ideal.span {g * e} := by
    intro x hx
    obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.mp hx
    refine Ideal.mem_span_singleton'.mpr ⟨c, ?_⟩
    simp only [LinearMap.toSpanSingleton_apply, smul_eq_mul]
    ring
  have hφ : Function.Bijective
      ((LinearMap.toSpanSingleton (Π i, R i) (Π i, R i) g).restrict hsub) := by
    constructor
    · rintro ⟨x, hx⟩ ⟨y, hy⟩ hxy
      have h1 : x • g = y • g := congrArg Subtype.val hxy
      refine Subtype.ext (sub_eq_zero.mp (hgreg _ ?_))
      rw [sub_mul, ← smul_eq_mul, ← smul_eq_mul, h1, sub_self]
    · rintro ⟨y, hy⟩
      obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.mp hy
      refine ⟨⟨c * e, Ideal.mem_span_singleton'.mpr ⟨c, rfl⟩⟩, Subtype.ext ?_⟩
      simp only [LinearMap.coe_restrict_apply, LinearMap.toSpanSingleton_apply, smul_eq_mul]
      ring
  exact Module.Flat.of_linearEquiv (LinearEquiv.ofBijective _ hφ).symm

/-- If `R` is of weak dimension `≤ 1`, it is integrally closed in any flat extension `S` such
that `R → S` is an epi. -/
lemma isIntegrallyClosedIn_of_isEpi [WeakDimensionLEOne R] [Module.Flat R S] [FaithfulSMul R S]
    [Algebra.IsEpi R S] :
    IsIntegrallyClosedIn R S := by
  rw [isIntegrallyClosedIn_iff]
  refine ⟨FaithfulSMul.algebraMap_injective R S, fun {x} hx ↦ ?_⟩
  let A := Algebra.adjoin R {x}
  have : Module.Finite R A := Algebra.finite_adjoin_simple_of_isIntegral hx
  have : Module.Flat R A := flat_submodule R (Subalgebra.toSubmodule A)
  have : Algebra.IsEpi R A := by
    rw [Algebra.isEpi_iff_forall_one_tmul_eq]
    intro a
    have hinj : Function.Injective ((TensorProduct.lift (LinearMap.mul R S)) ∘ₗ
        TensorProduct.map A.val.toLinearMap A.val.toLinearMap) :=
      Algebra.IsEpi.injective_lift_mul.comp <| TensorProduct.map_injective_of_flat_flat _ _
        Subtype.val_injective Subtype.val_injective
    exact hinj (by simp)
  obtain ⟨y, hy⟩ := (Algebra.isEpi_iff_surjective_algebraMap_of_finite (R := R) (A := A)).mp
    ‹_› ⟨x, Algebra.self_mem_adjoin_singleton R x⟩
  exact ⟨y, by simpa using congrArg Subtype.val hy⟩

end Ring.WeakDimensionLEOne

namespace Ring.AbsolutelyFlat

instance of_field (R : Type*) [Field R] : AbsolutelyFlat R where
  flat _ := inferInstance

variable (R : Type*) [CommRing R] (M : Type*) [AddCommGroup M] [Module R M]

lemma of_isField (h : IsField R) : AbsolutelyFlat R := @of_field R h.toField

lemma isField_of_isLocalRing [IsLocalRing R] [AbsolutelyFlat R] : IsField R := by
  apply Ring.isField_iff_maximal_bot.mpr
  suffices h : IsLocalRing.maximalIdeal R = ⊥ from h ▸ inferInstance
  refine le_antisymm (fun x hx ↦ ?_) bot_le
  obtain ⟨y, hy, hy'⟩ := exists_eq_mul_of_surjective_flat
    (Ideal.Quotient.mk (IsLocalRing.maximalIdeal R)) (AbsolutelyFlat.flat _)
    Ideal.Quotient.mk_surjective x (Ideal.Quotient.eq_zero_iff_mem.mpr hx)
  obtain ⟨y, rfl⟩ := IsLocalRing.notMem_maximalIdeal.mp
    fun hy'' ↦ one_ne_zero <| hy.symm.trans (Ideal.Quotient.eq_zero_iff_mem.mpr hy'')
  simpa using congr(y⁻¹ * $hy')

variable {R} in
lemma of_isLocalization [AbsolutelyFlat R] (s : Submonoid R)
    (S : Type*) [CommRing S] [Algebra R S] [IsLocalization s S] : AbsolutelyFlat S := by
  refine .mk fun I ↦ ?_
  -- `obtain` is used to erase the value so that `subst` doesn't give a recursive error.
  obtain ⟨I', hI'⟩ : ∃ I' : Ideal R, I' = I.comap (algebraMap R S) := ⟨_, rfl⟩
  have := AbsolutelyFlat.flat I'
  have : I = Submodule.localized' S s (Algebra.linearMap R S) I' := by
    simp only [Ideal.localized'_eq_map, hI', IsLocalization.map_under s S I]
  subst this
  let f := Submodule.toLocalizedQuotient' S s (Algebra.linearMap R S) I'
  exact Module.Flat.of_isLocalizedModule (R := R) (M := R ⧸ I') S s f

lemma localizationPreserves : LocalizationPreserves fun R _ ↦ AbsolutelyFlat R :=
    fun s S _ _ _ _ ↦ of_isLocalization s S

instance [AbsolutelyFlat R] (s : Submonoid R) : AbsolutelyFlat (Localization s) :=
  localizationPreserves s _ inferInstance

lemma isField_of_isLocalization_prime [AbsolutelyFlat R] (p : Ideal R) [p.IsPrime]
    (S : Type*) [CommRing S] [Algebra R S] [IsLocalization.AtPrime S p] :
    IsField S := @isField_of_isLocalRing _ _ (IsLocalization.AtPrime.isLocalRing S p)
  (of_isLocalization p.primeCompl S)

lemma _root_.Module.flat_of_localization_atPrime_isField
    (h : ∀ (P : Ideal R) [P.IsPrime], IsField (Localization.AtPrime P)) : Module.Flat R M := by
  refine Module.flat_of_localized_maximal (R := R) M fun P hP ↦ ?_
  suffices Module.Flat (Localization P.primeCompl) (LocalizedModule P.primeCompl M)
    from (Localization.flat R P.primeCompl).trans _ _ _
  let := (h P).toField
  infer_instance

instance [AbsolutelyFlat R] : Module.Flat R M :=
  Module.flat_of_localization_atPrime_isField _ _ (fun _ _ ↦ isField_of_isLocalRing _)

theorem tfae : [AbsolutelyFlat R,
    IsReduced R ∧ ∀ P : Ideal R, P.IsPrime → P.IsMaximal,
    IsReduced R ∧ Ring.KrullDimLE 0 R,
    ∀ (P : Ideal R) [P.IsPrime], IsField (Localization.AtPrime P)].TFAE := by
  tfae_have 1 ↔ 4 := ⟨fun _ _ ↦ isField_of_isLocalRing _,
    fun h ↦ .mk fun I ↦ Module.flat_of_localization_atPrime_isField _ _ h⟩
  tfae_have 2 ↔ 3 := and_congr_right_iff.mpr fun _ ↦ krullDimLE_zero_iff.symm
  tfae_have 2 → 4 := by
    rintro ⟨_, h'⟩ P hP
    have : KrullDimLE 0 (Localization.AtPrime P) := Ring.krullDimLE_iff.mpr <| le_trans
      (by simpa [IsLocalization.AtPrime.ringKrullDim_eq_height P] using
        P.height_le_ringKrullDim_of_ne_top hP.ne_top)
      ((Ring.krullDimLE_iff (R := R)).mp (.mk₀ h'))
    exact Ring.KrullDimLE.isField_of_isReduced
  tfae_have 4 → 2 := fun h ↦ by
    let (P : Ideal R) [P.IsPrime] := (h P).toField
    refine ⟨isReduced_ofLocalizationMaximal _ fun P hP ↦ ?_, Ring.krullDimLE_zero_iff.mp ?_⟩
    · infer_instance
    · exact Ring.krullDimLE_of_isLocalization_maximal (fun P hP ↦ Localization.AtPrime P)
        fun P hP ↦ inferInstance
  tfae_finish

instance (priority := low) [AbsolutelyFlat R] : IsReduced R := by
  have h : AbsolutelyFlat R ↔ IsReduced R ∧ ∀ P : Ideal R, P.IsPrime → P.IsMaximal :=
    (tfae R).out 0 1
  exact (h.mp ‹_›).1

variable (R S M : Type*) [CommRing R] [CommRing S] [Algebra R S]
    [AddCommGroup M] [Module R M] [Module S M] [IsScalarTower R S M]
    (h : (Algebra.TensorProduct.lmul' (S := S) R).Flat)

open TensorProduct

include h in
@[stacks 092C]
theorem _root_.Module.Flat.of_flat_lmul'_of_flat [Module.Flat R M] : Module.Flat S M := by
  refine Module.Flat.of_forall_isTrivialRelation fun {l f x} hx ↦ ?_
  obtain ⟨t, ht, ht'⟩ := exists_eq_mul_of_surjective_flat' _ h (fun x ↦ ⟨1 ⊗ₜ[R] x, by simp⟩)
    (fun i : Fin l ↦ (1 : S) ⊗ₜ[R] (f i) - (f i) ⊗ₜ[R] (1 : S)) (fun i ↦ by simp)
  obtain ⟨s, rfl⟩ := TensorProduct.exists_finset t
  simp only [AlgHom.toRingHom_eq_coe, map_sum, RingHom.coe_coe,
    Algebra.TensorProduct.lmul'_apply_tmul] at ht
  simp only [Finset.sum_mul, mul_sub, Algebra.TensorProduct.tmul_mul_tmul, sub_eq_zero] at ht'
  let φ (i : Fin l) : S ⊗[R] S →ₗ[R] S ⊗[R] M :=
    LinearMap.lTensor S (LinearMap.toSpanSingleton S M (x i))
  have hg : ∑ y : s ×ˢ Finset.univ, (y.1.1.1 * f y.1.2) ⊗ₜ[R] (y.1.1.2 • x y.1.2) = 0 := by
    simp only [Finset.sum_coe_sort _
        (fun y : (S × S) × Fin l ↦ (y.1.1 * f y.2) ⊗ₜ[R] (y.1.2 • x y.2)),
      Finset.sum_product, Finset.sum_comm (s := s)]
    replace ht' := by simpa [φ] using congr(fun i ↦ (φ i) $(ht' i))
    simp only [← ht', Finset.sum_comm (t := s), ← tmul_sum, mul_smul, ← Finset.smul_sum, hx,
      smul_zero, tmul_zero, Finset.sum_const_zero]
  obtain ⟨l', g, y, ha, ha'⟩ := vanishesTrivially_of_sum_tmul_eq_zero_of_rTensor_injective R
    (Module.Flat.rTensor_preserves_injective_linearMap _ (Submodule.subtype_injective _)) hg
  refine ⟨l', fun i j ↦ s.attach.sum fun x ↦ x.1.1 * (algebraMap R S) (g ⟨⟨x.1, i⟩, by simp⟩ j),
    y, fun i ↦ ?_, fun j ↦ ?_⟩
  · simp only [Finset.sum_smul, mul_smul, Finset.sum_comm, ← Finset.smul_sum, algebraMap_smul]
    simp only [← ha, ← mul_smul, ← Finset.sum_smul, ← Finset.sum_coe_sort_eq_attach,
      Finset.sum_coe_sort _ fun (i : S × S) ↦ i.1 * i.2, ht, one_smul]
  · simp only [Finset.mul_sum, ← ha' j, ← Finset.sum_product_right']
    exact Finset.sum_bij' (fun a _ ↦ ⟨⟨a.1, a.2⟩, by simp⟩) (fun a _ ↦ ⟨⟨a.1.1, by grind⟩, a.1.2⟩)
      (by simp) (by simp) (by simp) (by simp)
      (by simp_rw [← mul_assoc, mul_comm (f _), mul_comm (_ * _), Algebra.smul_def,
        forall_true_iff])

include h in
@[stacks 092I "(1)"]
theorem of_flat_lmul' [AbsolutelyFlat R] : AbsolutelyFlat S :=
  ⟨fun _ ↦ Module.Flat.of_flat_lmul'_of_flat R S _ h⟩

end Ring.AbsolutelyFlat

namespace Ring.WeakDimensionLEOne

variable (R : Type*) [CommRing R] {S : Type*} [CommRing S] [Algebra R S]

/-- If `R` is of weak dimension `≤ 1` and `S` is weakly étale over `R`, then the same holds for
`S`. -/
lemma of_weaklyEtale [Ring.WeakDimensionLEOne R] [Algebra.WeaklyEtale R S] :
    Ring.WeakDimensionLEOne S := by
  refine .mk fun I _ ↦ ?_
  have : Module.Flat R I := flat_submodule R (I.restrictScalars R)
  exact Module.Flat.of_flat_lmul'_of_flat R S I (Algebra.WeaklyEtale.flat_lmul' R S)

end Ring.WeakDimensionLEOne
