/-
Copyright (c) 2025 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Proetale.Topology.Comparison.Etale
import Proetale.Topology.Coherent.Affine
import Proetale.Pro.Basic

universe u

open CategoryTheory MorphismProperty Limits

namespace AlgebraicGeometry.Scheme

variable {S : Scheme.{u}}

/-- An object of the pro-étale site of `S` is pro-affine, if it can be written
as `limᵢ (Spec Aᵢ)` where `Spec Aᵢ` is an étale `S`-scheme. -/
def ProEt.proAffine (S : Scheme.{u}) : ObjectProperty S.ProEt :=
  fun X ↦ ∃ (J : Type u) (_ : SmallCategory J) (_ : IsCofiltered J),
    Nonempty (RelativeLimitPresentation J (AffineEtale.Spec S ⋙ S.toProEtale) X)

/-- The pro-étale affine site is the full subcategory of the pro-étale site where every
object can be written as a cofiltered limit of affine étale schemes over `S`. -/
def AffineProEt (S : Scheme.{u}) : Type (u + 1) :=
  (ProEt.proAffine S).FullSubcategory

variable (S : Scheme.{u})

noncomputable instance : Category S.AffineProEt :=
  inferInstanceAs <| Category <| ObjectProperty.FullSubcategory _

namespace AffineProEt

/-- The inclusion of the affine pro-étale site into the pro-étale site. -/
def toProEt (S : Scheme.{u}) : S.AffineProEt ⥤ S.ProEt :=
  (ProEt.proAffine S).ι

instance : (toProEt S).Full := inferInstanceAs <| (ProEt.proAffine S).ι.Full
instance : (toProEt S).Faithful := inferInstanceAs <| (ProEt.proAffine S).ι.Faithful

instance : (toProEt S).LocallyCoverDense (ProEt.topology S) :=
  sorry

def topology : GrothendieckTopology S.AffineProEt :=
  (toProEt S).inducedTopology (ProEt.topology S)

end AffineProEt

/-- The inclusion of the affine étale site into the affine pro-étale site. -/
noncomputable def AffineEtale.toAffineProEt (S : Scheme.{u}) :
    S.AffineEtale ⥤ S.AffineProEt :=
  ObjectProperty.lift _ (AffineEtale.Spec S ⋙ S.toProEtale) <| fun _ ↦
    ⟨PUnit, inferInstance, inferInstance, ⟨.self _⟩⟩

/-- The topology on the affine pro-étale site is generated by limits
of `1`-hypercovers in the affine étale site. -/
instance :
    (GrothendieckTopology.oneHypercoverRelativelyRepresentable.{u}
      (AffineEtale.toAffineProEt S) (Type u)
      (AffineEtale.topology S) (AffineProEt.topology S)).IsGenerating :=
  sorry

end AlgebraicGeometry.Scheme
